
server:
    port: ${random.int[10000,19999]}

eureka:
    instance:
        hostname: localhost
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 20
    client:
        registerWithEureka: true
        fetch-registry: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:8888/eureka/

