// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutedOrderBO.proto

package com.purefun.fams.trade.exec.pro;

public final class ExecutedOrderBO_PRO {
  private ExecutedOrderBO_PRO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExecutedOrderBOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExecutedOrderBO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>sint64 boid = 2;</code>
     * @return The boid.
     */
    long getBoid();

    /**
     * <code>string account = 4;</code>
     * @return The account.
     */
    java.lang.String getAccount();
    /**
     * <code>string account = 4;</code>
     * @return The bytes for account.
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>string security_code = 5;</code>
     * @return The securityCode.
     */
    java.lang.String getSecurityCode();
    /**
     * <code>string security_code = 5;</code>
     * @return The bytes for securityCode.
     */
    com.google.protobuf.ByteString
        getSecurityCodeBytes();

    /**
     * <code>string exch = 6;</code>
     * @return The exch.
     */
    java.lang.String getExch();
    /**
     * <code>string exch = 6;</code>
     * @return The bytes for exch.
     */
    com.google.protobuf.ByteString
        getExchBytes();

    /**
     * <code>string security_type = 7;</code>
     * @return The securityType.
     */
    java.lang.String getSecurityType();
    /**
     * <code>string security_type = 7;</code>
     * @return The bytes for securityType.
     */
    com.google.protobuf.ByteString
        getSecurityTypeBytes();

    /**
     * <code>string direction = 8;</code>
     * @return The direction.
     */
    java.lang.String getDirection();
    /**
     * <code>string direction = 8;</code>
     * @return The bytes for direction.
     */
    com.google.protobuf.ByteString
        getDirectionBytes();

    /**
     * <code>string orderId = 9;</code>
     * @return The orderId.
     */
    java.lang.String getOrderId();
    /**
     * <code>string orderId = 9;</code>
     * @return The bytes for orderId.
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>string tradeDate = 10;</code>
     * @return The tradeDate.
     */
    java.lang.String getTradeDate();
    /**
     * <code>string tradeDate = 10;</code>
     * @return The bytes for tradeDate.
     */
    com.google.protobuf.ByteString
        getTradeDateBytes();

    /**
     * <code>string executeId = 11;</code>
     * @return The executeId.
     */
    java.lang.String getExecuteId();
    /**
     * <code>string executeId = 11;</code>
     * @return The bytes for executeId.
     */
    com.google.protobuf.ByteString
        getExecuteIdBytes();

    /**
     * <code>double executePrice = 12;</code>
     * @return The executePrice.
     */
    double getExecutePrice();

    /**
     * <code>sint64 executeVolume = 13;</code>
     * @return The executeVolume.
     */
    long getExecuteVolume();
  }
  /**
   * Protobuf type {@code ExecutedOrderBO}
   */
  public  static final class ExecutedOrderBO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ExecutedOrderBO)
      ExecutedOrderBOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExecutedOrderBO.newBuilder() to construct.
    private ExecutedOrderBO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExecutedOrderBO() {
      uuid_ = "";
      account_ = "";
      securityCode_ = "";
      exch_ = "";
      securityType_ = "";
      direction_ = "";
      orderId_ = "";
      tradeDate_ = "";
      executeId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExecutedOrderBO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExecutedOrderBO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 16: {

              boid_ = input.readSInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              securityCode_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              exch_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              securityType_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              direction_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              orderId_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              tradeDate_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              executeId_ = s;
              break;
            }
            case 97: {

              executePrice_ = input.readDouble();
              break;
            }
            case 104: {

              executeVolume_ = input.readSInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.internal_static_ExecutedOrderBO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.internal_static_ExecutedOrderBO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO.class, com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOID_FIELD_NUMBER = 2;
    private long boid_;
    /**
     * <code>sint64 boid = 2;</code>
     * @return The boid.
     */
    public long getBoid() {
      return boid_;
    }

    public static final int ACCOUNT_FIELD_NUMBER = 4;
    private volatile java.lang.Object account_;
    /**
     * <code>string account = 4;</code>
     * @return The account.
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>string account = 4;</code>
     * @return The bytes for account.
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECURITY_CODE_FIELD_NUMBER = 5;
    private volatile java.lang.Object securityCode_;
    /**
     * <code>string security_code = 5;</code>
     * @return The securityCode.
     */
    public java.lang.String getSecurityCode() {
      java.lang.Object ref = securityCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityCode_ = s;
        return s;
      }
    }
    /**
     * <code>string security_code = 5;</code>
     * @return The bytes for securityCode.
     */
    public com.google.protobuf.ByteString
        getSecurityCodeBytes() {
      java.lang.Object ref = securityCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCH_FIELD_NUMBER = 6;
    private volatile java.lang.Object exch_;
    /**
     * <code>string exch = 6;</code>
     * @return The exch.
     */
    public java.lang.String getExch() {
      java.lang.Object ref = exch_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exch_ = s;
        return s;
      }
    }
    /**
     * <code>string exch = 6;</code>
     * @return The bytes for exch.
     */
    public com.google.protobuf.ByteString
        getExchBytes() {
      java.lang.Object ref = exch_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECURITY_TYPE_FIELD_NUMBER = 7;
    private volatile java.lang.Object securityType_;
    /**
     * <code>string security_type = 7;</code>
     * @return The securityType.
     */
    public java.lang.String getSecurityType() {
      java.lang.Object ref = securityType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityType_ = s;
        return s;
      }
    }
    /**
     * <code>string security_type = 7;</code>
     * @return The bytes for securityType.
     */
    public com.google.protobuf.ByteString
        getSecurityTypeBytes() {
      java.lang.Object ref = securityType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTION_FIELD_NUMBER = 8;
    private volatile java.lang.Object direction_;
    /**
     * <code>string direction = 8;</code>
     * @return The direction.
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      }
    }
    /**
     * <code>string direction = 8;</code>
     * @return The bytes for direction.
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERID_FIELD_NUMBER = 9;
    private volatile java.lang.Object orderId_;
    /**
     * <code>string orderId = 9;</code>
     * @return The orderId.
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      }
    }
    /**
     * <code>string orderId = 9;</code>
     * @return The bytes for orderId.
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRADEDATE_FIELD_NUMBER = 10;
    private volatile java.lang.Object tradeDate_;
    /**
     * <code>string tradeDate = 10;</code>
     * @return The tradeDate.
     */
    public java.lang.String getTradeDate() {
      java.lang.Object ref = tradeDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tradeDate_ = s;
        return s;
      }
    }
    /**
     * <code>string tradeDate = 10;</code>
     * @return The bytes for tradeDate.
     */
    public com.google.protobuf.ByteString
        getTradeDateBytes() {
      java.lang.Object ref = tradeDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tradeDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXECUTEID_FIELD_NUMBER = 11;
    private volatile java.lang.Object executeId_;
    /**
     * <code>string executeId = 11;</code>
     * @return The executeId.
     */
    public java.lang.String getExecuteId() {
      java.lang.Object ref = executeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        executeId_ = s;
        return s;
      }
    }
    /**
     * <code>string executeId = 11;</code>
     * @return The bytes for executeId.
     */
    public com.google.protobuf.ByteString
        getExecuteIdBytes() {
      java.lang.Object ref = executeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        executeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXECUTEPRICE_FIELD_NUMBER = 12;
    private double executePrice_;
    /**
     * <code>double executePrice = 12;</code>
     * @return The executePrice.
     */
    public double getExecutePrice() {
      return executePrice_;
    }

    public static final int EXECUTEVOLUME_FIELD_NUMBER = 13;
    private long executeVolume_;
    /**
     * <code>sint64 executeVolume = 13;</code>
     * @return The executeVolume.
     */
    public long getExecuteVolume() {
      return executeVolume_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (boid_ != 0L) {
        output.writeSInt64(2, boid_);
      }
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, account_);
      }
      if (!getSecurityCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, securityCode_);
      }
      if (!getExchBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, exch_);
      }
      if (!getSecurityTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, securityType_);
      }
      if (!getDirectionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, direction_);
      }
      if (!getOrderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, orderId_);
      }
      if (!getTradeDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, tradeDate_);
      }
      if (!getExecuteIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, executeId_);
      }
      if (executePrice_ != 0D) {
        output.writeDouble(12, executePrice_);
      }
      if (executeVolume_ != 0L) {
        output.writeSInt64(13, executeVolume_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (boid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, boid_);
      }
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, account_);
      }
      if (!getSecurityCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, securityCode_);
      }
      if (!getExchBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, exch_);
      }
      if (!getSecurityTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, securityType_);
      }
      if (!getDirectionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, direction_);
      }
      if (!getOrderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, orderId_);
      }
      if (!getTradeDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, tradeDate_);
      }
      if (!getExecuteIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, executeId_);
      }
      if (executePrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, executePrice_);
      }
      if (executeVolume_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(13, executeVolume_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO)) {
        return super.equals(obj);
      }
      com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO other = (com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO) obj;

      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (getBoid()
          != other.getBoid()) return false;
      if (!getAccount()
          .equals(other.getAccount())) return false;
      if (!getSecurityCode()
          .equals(other.getSecurityCode())) return false;
      if (!getExch()
          .equals(other.getExch())) return false;
      if (!getSecurityType()
          .equals(other.getSecurityType())) return false;
      if (!getDirection()
          .equals(other.getDirection())) return false;
      if (!getOrderId()
          .equals(other.getOrderId())) return false;
      if (!getTradeDate()
          .equals(other.getTradeDate())) return false;
      if (!getExecuteId()
          .equals(other.getExecuteId())) return false;
      if (java.lang.Double.doubleToLongBits(getExecutePrice())
          != java.lang.Double.doubleToLongBits(
              other.getExecutePrice())) return false;
      if (getExecuteVolume()
          != other.getExecuteVolume()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + BOID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBoid());
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + SECURITY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityCode().hashCode();
      hash = (37 * hash) + EXCH_FIELD_NUMBER;
      hash = (53 * hash) + getExch().hashCode();
      hash = (37 * hash) + SECURITY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityType().hashCode();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId().hashCode();
      hash = (37 * hash) + TRADEDATE_FIELD_NUMBER;
      hash = (53 * hash) + getTradeDate().hashCode();
      hash = (37 * hash) + EXECUTEID_FIELD_NUMBER;
      hash = (53 * hash) + getExecuteId().hashCode();
      hash = (37 * hash) + EXECUTEPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getExecutePrice()));
      hash = (37 * hash) + EXECUTEVOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecuteVolume());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExecutedOrderBO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExecutedOrderBO)
        com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.internal_static_ExecutedOrderBO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.internal_static_ExecutedOrderBO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO.class, com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO.Builder.class);
      }

      // Construct using com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uuid_ = "";

        boid_ = 0L;

        account_ = "";

        securityCode_ = "";

        exch_ = "";

        securityType_ = "";

        direction_ = "";

        orderId_ = "";

        tradeDate_ = "";

        executeId_ = "";

        executePrice_ = 0D;

        executeVolume_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.internal_static_ExecutedOrderBO_descriptor;
      }

      @java.lang.Override
      public com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO getDefaultInstanceForType() {
        return com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO.getDefaultInstance();
      }

      @java.lang.Override
      public com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO build() {
        com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO buildPartial() {
        com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO result = new com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO(this);
        result.uuid_ = uuid_;
        result.boid_ = boid_;
        result.account_ = account_;
        result.securityCode_ = securityCode_;
        result.exch_ = exch_;
        result.securityType_ = securityType_;
        result.direction_ = direction_;
        result.orderId_ = orderId_;
        result.tradeDate_ = tradeDate_;
        result.executeId_ = executeId_;
        result.executePrice_ = executePrice_;
        result.executeVolume_ = executeVolume_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO) {
          return mergeFrom((com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO other) {
        if (other == com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.getBoid() != 0L) {
          setBoid(other.getBoid());
        }
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (!other.getSecurityCode().isEmpty()) {
          securityCode_ = other.securityCode_;
          onChanged();
        }
        if (!other.getExch().isEmpty()) {
          exch_ = other.exch_;
          onChanged();
        }
        if (!other.getSecurityType().isEmpty()) {
          securityType_ = other.securityType_;
          onChanged();
        }
        if (!other.getDirection().isEmpty()) {
          direction_ = other.direction_;
          onChanged();
        }
        if (!other.getOrderId().isEmpty()) {
          orderId_ = other.orderId_;
          onChanged();
        }
        if (!other.getTradeDate().isEmpty()) {
          tradeDate_ = other.tradeDate_;
          onChanged();
        }
        if (!other.getExecuteId().isEmpty()) {
          executeId_ = other.executeId_;
          onChanged();
        }
        if (other.getExecutePrice() != 0D) {
          setExecutePrice(other.getExecutePrice());
        }
        if (other.getExecuteVolume() != 0L) {
          setExecuteVolume(other.getExecuteVolume());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private long boid_ ;
      /**
       * <code>sint64 boid = 2;</code>
       * @return The boid.
       */
      public long getBoid() {
        return boid_;
      }
      /**
       * <code>sint64 boid = 2;</code>
       * @param value The boid to set.
       * @return This builder for chaining.
       */
      public Builder setBoid(long value) {
        
        boid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 boid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoid() {
        
        boid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>string account = 4;</code>
       * @return The account.
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account = 4;</code>
       * @return The bytes for account.
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account = 4;</code>
       * @param value The account to set.
       * @return This builder for chaining.
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>string account = 4;</code>
       * @param value The bytes for account to set.
       * @return This builder for chaining.
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object securityCode_ = "";
      /**
       * <code>string security_code = 5;</code>
       * @return The securityCode.
       */
      public java.lang.String getSecurityCode() {
        java.lang.Object ref = securityCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          securityCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string security_code = 5;</code>
       * @return The bytes for securityCode.
       */
      public com.google.protobuf.ByteString
          getSecurityCodeBytes() {
        java.lang.Object ref = securityCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string security_code = 5;</code>
       * @param value The securityCode to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        securityCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string security_code = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityCode() {
        
        securityCode_ = getDefaultInstance().getSecurityCode();
        onChanged();
        return this;
      }
      /**
       * <code>string security_code = 5;</code>
       * @param value The bytes for securityCode to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        securityCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exch_ = "";
      /**
       * <code>string exch = 6;</code>
       * @return The exch.
       */
      public java.lang.String getExch() {
        java.lang.Object ref = exch_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exch_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exch = 6;</code>
       * @return The bytes for exch.
       */
      public com.google.protobuf.ByteString
          getExchBytes() {
        java.lang.Object ref = exch_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exch_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exch = 6;</code>
       * @param value The exch to set.
       * @return This builder for chaining.
       */
      public Builder setExch(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exch = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearExch() {
        
        exch_ = getDefaultInstance().getExch();
        onChanged();
        return this;
      }
      /**
       * <code>string exch = 6;</code>
       * @param value The bytes for exch to set.
       * @return This builder for chaining.
       */
      public Builder setExchBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exch_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object securityType_ = "";
      /**
       * <code>string security_type = 7;</code>
       * @return The securityType.
       */
      public java.lang.String getSecurityType() {
        java.lang.Object ref = securityType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          securityType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string security_type = 7;</code>
       * @return The bytes for securityType.
       */
      public com.google.protobuf.ByteString
          getSecurityTypeBytes() {
        java.lang.Object ref = securityType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string security_type = 7;</code>
       * @param value The securityType to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        securityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string security_type = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityType() {
        
        securityType_ = getDefaultInstance().getSecurityType();
        onChanged();
        return this;
      }
      /**
       * <code>string security_type = 7;</code>
       * @param value The bytes for securityType to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        securityType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object direction_ = "";
      /**
       * <code>string direction = 8;</code>
       * @return The direction.
       */
      public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string direction = 8;</code>
       * @return The bytes for direction.
       */
      public com.google.protobuf.ByteString
          getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string direction = 8;</code>
       * @param value The direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirection() {
        
        direction_ = getDefaultInstance().getDirection();
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 8;</code>
       * @param value The bytes for direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        direction_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>string orderId = 9;</code>
       * @return The orderId.
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderId = 9;</code>
       * @return The bytes for orderId.
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderId = 9;</code>
       * @param value The orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderId() {
        
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 9;</code>
       * @param value The bytes for orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tradeDate_ = "";
      /**
       * <code>string tradeDate = 10;</code>
       * @return The tradeDate.
       */
      public java.lang.String getTradeDate() {
        java.lang.Object ref = tradeDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tradeDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tradeDate = 10;</code>
       * @return The bytes for tradeDate.
       */
      public com.google.protobuf.ByteString
          getTradeDateBytes() {
        java.lang.Object ref = tradeDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tradeDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tradeDate = 10;</code>
       * @param value The tradeDate to set.
       * @return This builder for chaining.
       */
      public Builder setTradeDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tradeDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tradeDate = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearTradeDate() {
        
        tradeDate_ = getDefaultInstance().getTradeDate();
        onChanged();
        return this;
      }
      /**
       * <code>string tradeDate = 10;</code>
       * @param value The bytes for tradeDate to set.
       * @return This builder for chaining.
       */
      public Builder setTradeDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tradeDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object executeId_ = "";
      /**
       * <code>string executeId = 11;</code>
       * @return The executeId.
       */
      public java.lang.String getExecuteId() {
        java.lang.Object ref = executeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          executeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string executeId = 11;</code>
       * @return The bytes for executeId.
       */
      public com.google.protobuf.ByteString
          getExecuteIdBytes() {
        java.lang.Object ref = executeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          executeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string executeId = 11;</code>
       * @param value The executeId to set.
       * @return This builder for chaining.
       */
      public Builder setExecuteId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        executeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string executeId = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecuteId() {
        
        executeId_ = getDefaultInstance().getExecuteId();
        onChanged();
        return this;
      }
      /**
       * <code>string executeId = 11;</code>
       * @param value The bytes for executeId to set.
       * @return This builder for chaining.
       */
      public Builder setExecuteIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        executeId_ = value;
        onChanged();
        return this;
      }

      private double executePrice_ ;
      /**
       * <code>double executePrice = 12;</code>
       * @return The executePrice.
       */
      public double getExecutePrice() {
        return executePrice_;
      }
      /**
       * <code>double executePrice = 12;</code>
       * @param value The executePrice to set.
       * @return This builder for chaining.
       */
      public Builder setExecutePrice(double value) {
        
        executePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double executePrice = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecutePrice() {
        
        executePrice_ = 0D;
        onChanged();
        return this;
      }

      private long executeVolume_ ;
      /**
       * <code>sint64 executeVolume = 13;</code>
       * @return The executeVolume.
       */
      public long getExecuteVolume() {
        return executeVolume_;
      }
      /**
       * <code>sint64 executeVolume = 13;</code>
       * @param value The executeVolume to set.
       * @return This builder for chaining.
       */
      public Builder setExecuteVolume(long value) {
        
        executeVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 executeVolume = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecuteVolume() {
        
        executeVolume_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ExecutedOrderBO)
    }

    // @@protoc_insertion_point(class_scope:ExecutedOrderBO)
    private static final com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO();
    }

    public static com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExecutedOrderBO>
        PARSER = new com.google.protobuf.AbstractParser<ExecutedOrderBO>() {
      @java.lang.Override
      public ExecutedOrderBO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExecutedOrderBO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExecutedOrderBO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExecutedOrderBO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.purefun.fams.trade.exec.pro.ExecutedOrderBO_PRO.ExecutedOrderBO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExecutedOrderBO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExecutedOrderBO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ExecutedOrderBO.proto\"\361\001\n\017ExecutedOrde" +
      "rBO\022\014\n\004uuid\030\001 \001(\t\022\014\n\004boid\030\002 \001(\022\022\017\n\007accou" +
      "nt\030\004 \001(\t\022\025\n\rsecurity_code\030\005 \001(\t\022\014\n\004exch\030" +
      "\006 \001(\t\022\025\n\rsecurity_type\030\007 \001(\t\022\021\n\tdirectio" +
      "n\030\010 \001(\t\022\017\n\007orderId\030\t \001(\t\022\021\n\ttradeDate\030\n " +
      "\001(\t\022\021\n\texecuteId\030\013 \001(\t\022\024\n\014executePrice\030\014" +
      " \001(\001\022\025\n\rexecuteVolume\030\r \001(\022B6\n\037com.puref" +
      "un.fams.trade.exec.proB\023ExecutedOrderBO_" +
      "PROb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ExecutedOrderBO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExecutedOrderBO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExecutedOrderBO_descriptor,
        new java.lang.String[] { "Uuid", "Boid", "Account", "SecurityCode", "Exch", "SecurityType", "Direction", "OrderId", "TradeDate", "ExecuteId", "ExecutePrice", "ExecuteVolume", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
