logging:
    file= classpath:log4j2.xml 
    
server:
    port: ${server.port}
    
fams:
    framework:
        service:
            serviceName: ${ServiceName}-${Env}

management:
  endpoints:
    web:
      exposure:
        include: service-registry
      
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: ${ServiceName}-${Env} 
    kafka:
        bootstrap-servers: localhost:9092
        listener:
            missing-topics-fatal: false
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        consumer:
            group-id: test
            enable-auto-commit: true
            auto-commit-interval: 1000
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer 
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/fams?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        username: root
        password: jianghan0712
        driver-class-name: com.mysql.jdbc.Driver
        max-idle: 10
        max-wait: 10000
        initial-size: 5
    redis:
        host: localhost
        port: 6379
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0
        timeout: 3000

mybatis:
    mapper-locations: classpath*:mapper/*.xml
