// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MdBarDataBO.proto

package com.purefun.fams.md.pro;

public final class MdBarDataBO_PRO {
  private MdBarDataBO_PRO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MdBarDataBOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MdBarDataBO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uuid = 1;</code>
     * @return Whether the uuid field is set.
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 1;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional sint64 boid = 2;</code>
     * @return Whether the boid field is set.
     */
    boolean hasBoid();
    /**
     * <code>optional sint64 boid = 2;</code>
     * @return The boid.
     */
    long getBoid();

    /**
     * <code>optional string destination = 3;</code>
     * @return Whether the destination field is set.
     */
    boolean hasDestination();
    /**
     * <code>optional string destination = 3;</code>
     * @return The destination.
     */
    java.lang.String getDestination();
    /**
     * <code>optional string destination = 3;</code>
     * @return The bytes for destination.
     */
    com.google.protobuf.ByteString
        getDestinationBytes();

    /**
     * <code>optional string security_code = 4;</code>
     * @return Whether the securityCode field is set.
     */
    boolean hasSecurityCode();
    /**
     * <code>optional string security_code = 4;</code>
     * @return The securityCode.
     */
    java.lang.String getSecurityCode();
    /**
     * <code>optional string security_code = 4;</code>
     * @return The bytes for securityCode.
     */
    com.google.protobuf.ByteString
        getSecurityCodeBytes();

    /**
     * <code>optional string exch = 5;</code>
     * @return Whether the exch field is set.
     */
    boolean hasExch();
    /**
     * <code>optional string exch = 5;</code>
     * @return The exch.
     */
    java.lang.String getExch();
    /**
     * <code>optional string exch = 5;</code>
     * @return The bytes for exch.
     */
    com.google.protobuf.ByteString
        getExchBytes();

    /**
     * <code>optional string security_type = 6;</code>
     * @return Whether the securityType field is set.
     */
    boolean hasSecurityType();
    /**
     * <code>optional string security_type = 6;</code>
     * @return The securityType.
     */
    java.lang.String getSecurityType();
    /**
     * <code>optional string security_type = 6;</code>
     * @return The bytes for securityType.
     */
    com.google.protobuf.ByteString
        getSecurityTypeBytes();

    /**
     * <code>optional string date = 7;</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>optional string date = 7;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>optional string date = 7;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>optional double open = 8;</code>
     * @return Whether the open field is set.
     */
    boolean hasOpen();
    /**
     * <code>optional double open = 8;</code>
     * @return The open.
     */
    double getOpen();

    /**
     * <code>optional double high = 9;</code>
     * @return Whether the high field is set.
     */
    boolean hasHigh();
    /**
     * <code>optional double high = 9;</code>
     * @return The high.
     */
    double getHigh();

    /**
     * <code>optional double low = 10;</code>
     * @return Whether the low field is set.
     */
    boolean hasLow();
    /**
     * <code>optional double low = 10;</code>
     * @return The low.
     */
    double getLow();

    /**
     * <code>optional double close = 11;</code>
     * @return Whether the close field is set.
     */
    boolean hasClose();
    /**
     * <code>optional double close = 11;</code>
     * @return The close.
     */
    double getClose();

    /**
     * <code>optional sint64 volume = 12;</code>
     * @return Whether the volume field is set.
     */
    boolean hasVolume();
    /**
     * <code>optional sint64 volume = 12;</code>
     * @return The volume.
     */
    long getVolume();

    /**
     * <code>optional double change = 13;</code>
     * @return Whether the change field is set.
     */
    boolean hasChange();
    /**
     * <code>optional double change = 13;</code>
     * @return The change.
     */
    double getChange();

    /**
     * <code>optional double pre_close = 14;</code>
     * @return Whether the preClose field is set.
     */
    boolean hasPreClose();
    /**
     * <code>optional double pre_close = 14;</code>
     * @return The preClose.
     */
    double getPreClose();

    /**
     * <code>optional double pct_chg = 15;</code>
     * @return Whether the pctChg field is set.
     */
    boolean hasPctChg();
    /**
     * <code>optional double pct_chg = 15;</code>
     * @return The pctChg.
     */
    double getPctChg();

    /**
     * <code>optional double amount = 16;</code>
     * @return Whether the amount field is set.
     */
    boolean hasAmount();
    /**
     * <code>optional double amount = 16;</code>
     * @return The amount.
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code MdBarDataBO}
   */
  public  static final class MdBarDataBO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MdBarDataBO)
      MdBarDataBOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MdBarDataBO.newBuilder() to construct.
    private MdBarDataBO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MdBarDataBO() {
      uuid_ = "";
      destination_ = "";
      securityCode_ = "";
      exch_ = "";
      securityType_ = "";
      date_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MdBarDataBO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MdBarDataBO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uuid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              boid_ = input.readSInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              destination_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              securityCode_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              exch_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              securityType_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              date_ = bs;
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              open_ = input.readDouble();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              high_ = input.readDouble();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000200;
              low_ = input.readDouble();
              break;
            }
            case 89: {
              bitField0_ |= 0x00000400;
              close_ = input.readDouble();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              volume_ = input.readSInt64();
              break;
            }
            case 105: {
              bitField0_ |= 0x00001000;
              change_ = input.readDouble();
              break;
            }
            case 113: {
              bitField0_ |= 0x00002000;
              preClose_ = input.readDouble();
              break;
            }
            case 121: {
              bitField0_ |= 0x00004000;
              pctChg_ = input.readDouble();
              break;
            }
            case 129: {
              bitField0_ |= 0x00008000;
              amount_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.purefun.fams.md.pro.MdBarDataBO_PRO.internal_static_MdBarDataBO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.purefun.fams.md.pro.MdBarDataBO_PRO.internal_static_MdBarDataBO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO.class, com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 1;</code>
     * @return Whether the uuid field is set.
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOID_FIELD_NUMBER = 2;
    private long boid_;
    /**
     * <code>optional sint64 boid = 2;</code>
     * @return Whether the boid field is set.
     */
    public boolean hasBoid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional sint64 boid = 2;</code>
     * @return The boid.
     */
    public long getBoid() {
      return boid_;
    }

    public static final int DESTINATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object destination_;
    /**
     * <code>optional string destination = 3;</code>
     * @return Whether the destination field is set.
     */
    public boolean hasDestination() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string destination = 3;</code>
     * @return The destination.
     */
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destination_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destination = 3;</code>
     * @return The bytes for destination.
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECURITY_CODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object securityCode_;
    /**
     * <code>optional string security_code = 4;</code>
     * @return Whether the securityCode field is set.
     */
    public boolean hasSecurityCode() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string security_code = 4;</code>
     * @return The securityCode.
     */
    public java.lang.String getSecurityCode() {
      java.lang.Object ref = securityCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          securityCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string security_code = 4;</code>
     * @return The bytes for securityCode.
     */
    public com.google.protobuf.ByteString
        getSecurityCodeBytes() {
      java.lang.Object ref = securityCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCH_FIELD_NUMBER = 5;
    private volatile java.lang.Object exch_;
    /**
     * <code>optional string exch = 5;</code>
     * @return Whether the exch field is set.
     */
    public boolean hasExch() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string exch = 5;</code>
     * @return The exch.
     */
    public java.lang.String getExch() {
      java.lang.Object ref = exch_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exch_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string exch = 5;</code>
     * @return The bytes for exch.
     */
    public com.google.protobuf.ByteString
        getExchBytes() {
      java.lang.Object ref = exch_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECURITY_TYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object securityType_;
    /**
     * <code>optional string security_type = 6;</code>
     * @return Whether the securityType field is set.
     */
    public boolean hasSecurityType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string security_type = 6;</code>
     * @return The securityType.
     */
    public java.lang.String getSecurityType() {
      java.lang.Object ref = securityType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          securityType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string security_type = 6;</code>
     * @return The bytes for securityType.
     */
    public com.google.protobuf.ByteString
        getSecurityTypeBytes() {
      java.lang.Object ref = securityType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 7;
    private volatile java.lang.Object date_;
    /**
     * <code>optional string date = 7;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string date = 7;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string date = 7;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPEN_FIELD_NUMBER = 8;
    private double open_;
    /**
     * <code>optional double open = 8;</code>
     * @return Whether the open field is set.
     */
    public boolean hasOpen() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional double open = 8;</code>
     * @return The open.
     */
    public double getOpen() {
      return open_;
    }

    public static final int HIGH_FIELD_NUMBER = 9;
    private double high_;
    /**
     * <code>optional double high = 9;</code>
     * @return Whether the high field is set.
     */
    public boolean hasHigh() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional double high = 9;</code>
     * @return The high.
     */
    public double getHigh() {
      return high_;
    }

    public static final int LOW_FIELD_NUMBER = 10;
    private double low_;
    /**
     * <code>optional double low = 10;</code>
     * @return Whether the low field is set.
     */
    public boolean hasLow() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional double low = 10;</code>
     * @return The low.
     */
    public double getLow() {
      return low_;
    }

    public static final int CLOSE_FIELD_NUMBER = 11;
    private double close_;
    /**
     * <code>optional double close = 11;</code>
     * @return Whether the close field is set.
     */
    public boolean hasClose() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional double close = 11;</code>
     * @return The close.
     */
    public double getClose() {
      return close_;
    }

    public static final int VOLUME_FIELD_NUMBER = 12;
    private long volume_;
    /**
     * <code>optional sint64 volume = 12;</code>
     * @return Whether the volume field is set.
     */
    public boolean hasVolume() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional sint64 volume = 12;</code>
     * @return The volume.
     */
    public long getVolume() {
      return volume_;
    }

    public static final int CHANGE_FIELD_NUMBER = 13;
    private double change_;
    /**
     * <code>optional double change = 13;</code>
     * @return Whether the change field is set.
     */
    public boolean hasChange() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>optional double change = 13;</code>
     * @return The change.
     */
    public double getChange() {
      return change_;
    }

    public static final int PRE_CLOSE_FIELD_NUMBER = 14;
    private double preClose_;
    /**
     * <code>optional double pre_close = 14;</code>
     * @return Whether the preClose field is set.
     */
    public boolean hasPreClose() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>optional double pre_close = 14;</code>
     * @return The preClose.
     */
    public double getPreClose() {
      return preClose_;
    }

    public static final int PCT_CHG_FIELD_NUMBER = 15;
    private double pctChg_;
    /**
     * <code>optional double pct_chg = 15;</code>
     * @return Whether the pctChg field is set.
     */
    public boolean hasPctChg() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>optional double pct_chg = 15;</code>
     * @return The pctChg.
     */
    public double getPctChg() {
      return pctChg_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 16;
    private double amount_;
    /**
     * <code>optional double amount = 16;</code>
     * @return Whether the amount field is set.
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <code>optional double amount = 16;</code>
     * @return The amount.
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeSInt64(2, boid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, destination_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, securityCode_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, exch_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, securityType_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, date_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeDouble(8, open_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeDouble(9, high_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeDouble(10, low_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeDouble(11, close_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeSInt64(12, volume_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        output.writeDouble(13, change_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        output.writeDouble(14, preClose_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        output.writeDouble(15, pctChg_);
      }
      if (((bitField0_ & 0x00008000) != 0)) {
        output.writeDouble(16, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, boid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, destination_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, securityCode_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, exch_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, securityType_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, date_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, open_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, high_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, low_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, close_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(12, volume_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, change_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, preClose_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(15, pctChg_);
      }
      if (((bitField0_ & 0x00008000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(16, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO)) {
        return super.equals(obj);
      }
      com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO other = (com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO) obj;

      if (hasUuid() != other.hasUuid()) return false;
      if (hasUuid()) {
        if (!getUuid()
            .equals(other.getUuid())) return false;
      }
      if (hasBoid() != other.hasBoid()) return false;
      if (hasBoid()) {
        if (getBoid()
            != other.getBoid()) return false;
      }
      if (hasDestination() != other.hasDestination()) return false;
      if (hasDestination()) {
        if (!getDestination()
            .equals(other.getDestination())) return false;
      }
      if (hasSecurityCode() != other.hasSecurityCode()) return false;
      if (hasSecurityCode()) {
        if (!getSecurityCode()
            .equals(other.getSecurityCode())) return false;
      }
      if (hasExch() != other.hasExch()) return false;
      if (hasExch()) {
        if (!getExch()
            .equals(other.getExch())) return false;
      }
      if (hasSecurityType() != other.hasSecurityType()) return false;
      if (hasSecurityType()) {
        if (!getSecurityType()
            .equals(other.getSecurityType())) return false;
      }
      if (hasDate() != other.hasDate()) return false;
      if (hasDate()) {
        if (!getDate()
            .equals(other.getDate())) return false;
      }
      if (hasOpen() != other.hasOpen()) return false;
      if (hasOpen()) {
        if (java.lang.Double.doubleToLongBits(getOpen())
            != java.lang.Double.doubleToLongBits(
                other.getOpen())) return false;
      }
      if (hasHigh() != other.hasHigh()) return false;
      if (hasHigh()) {
        if (java.lang.Double.doubleToLongBits(getHigh())
            != java.lang.Double.doubleToLongBits(
                other.getHigh())) return false;
      }
      if (hasLow() != other.hasLow()) return false;
      if (hasLow()) {
        if (java.lang.Double.doubleToLongBits(getLow())
            != java.lang.Double.doubleToLongBits(
                other.getLow())) return false;
      }
      if (hasClose() != other.hasClose()) return false;
      if (hasClose()) {
        if (java.lang.Double.doubleToLongBits(getClose())
            != java.lang.Double.doubleToLongBits(
                other.getClose())) return false;
      }
      if (hasVolume() != other.hasVolume()) return false;
      if (hasVolume()) {
        if (getVolume()
            != other.getVolume()) return false;
      }
      if (hasChange() != other.hasChange()) return false;
      if (hasChange()) {
        if (java.lang.Double.doubleToLongBits(getChange())
            != java.lang.Double.doubleToLongBits(
                other.getChange())) return false;
      }
      if (hasPreClose() != other.hasPreClose()) return false;
      if (hasPreClose()) {
        if (java.lang.Double.doubleToLongBits(getPreClose())
            != java.lang.Double.doubleToLongBits(
                other.getPreClose())) return false;
      }
      if (hasPctChg() != other.hasPctChg()) return false;
      if (hasPctChg()) {
        if (java.lang.Double.doubleToLongBits(getPctChg())
            != java.lang.Double.doubleToLongBits(
                other.getPctChg())) return false;
      }
      if (hasAmount() != other.hasAmount()) return false;
      if (hasAmount()) {
        if (java.lang.Double.doubleToLongBits(getAmount())
            != java.lang.Double.doubleToLongBits(
                other.getAmount())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasBoid()) {
        hash = (37 * hash) + BOID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBoid());
      }
      if (hasDestination()) {
        hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
        hash = (53 * hash) + getDestination().hashCode();
      }
      if (hasSecurityCode()) {
        hash = (37 * hash) + SECURITY_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getSecurityCode().hashCode();
      }
      if (hasExch()) {
        hash = (37 * hash) + EXCH_FIELD_NUMBER;
        hash = (53 * hash) + getExch().hashCode();
      }
      if (hasSecurityType()) {
        hash = (37 * hash) + SECURITY_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSecurityType().hashCode();
      }
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      if (hasOpen()) {
        hash = (37 * hash) + OPEN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getOpen()));
      }
      if (hasHigh()) {
        hash = (37 * hash) + HIGH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getHigh()));
      }
      if (hasLow()) {
        hash = (37 * hash) + LOW_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLow()));
      }
      if (hasClose()) {
        hash = (37 * hash) + CLOSE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getClose()));
      }
      if (hasVolume()) {
        hash = (37 * hash) + VOLUME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getVolume());
      }
      if (hasChange()) {
        hash = (37 * hash) + CHANGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getChange()));
      }
      if (hasPreClose()) {
        hash = (37 * hash) + PRE_CLOSE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPreClose()));
      }
      if (hasPctChg()) {
        hash = (37 * hash) + PCT_CHG_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPctChg()));
      }
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getAmount()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MdBarDataBO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MdBarDataBO)
        com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.purefun.fams.md.pro.MdBarDataBO_PRO.internal_static_MdBarDataBO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.purefun.fams.md.pro.MdBarDataBO_PRO.internal_static_MdBarDataBO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO.class, com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO.Builder.class);
      }

      // Construct using com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        boid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        destination_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        securityCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        exch_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        securityType_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        open_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        high_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        low_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000200);
        close_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000400);
        volume_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        change_ = 0D;
        bitField0_ = (bitField0_ & ~0x00001000);
        preClose_ = 0D;
        bitField0_ = (bitField0_ & ~0x00002000);
        pctChg_ = 0D;
        bitField0_ = (bitField0_ & ~0x00004000);
        amount_ = 0D;
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.purefun.fams.md.pro.MdBarDataBO_PRO.internal_static_MdBarDataBO_descriptor;
      }

      @java.lang.Override
      public com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO getDefaultInstanceForType() {
        return com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO.getDefaultInstance();
      }

      @java.lang.Override
      public com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO build() {
        com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO buildPartial() {
        com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO result = new com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.boid_ = boid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destination_ = destination_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.securityCode_ = securityCode_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.exch_ = exch_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.securityType_ = securityType_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.open_ = open_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.high_ = high_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.low_ = low_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.close_ = close_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.volume_ = volume_;
          to_bitField0_ |= 0x00000800;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.change_ = change_;
          to_bitField0_ |= 0x00001000;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.preClose_ = preClose_;
          to_bitField0_ |= 0x00002000;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.pctChg_ = pctChg_;
          to_bitField0_ |= 0x00004000;
        }
        if (((from_bitField0_ & 0x00008000) != 0)) {
          result.amount_ = amount_;
          to_bitField0_ |= 0x00008000;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO) {
          return mergeFrom((com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO other) {
        if (other == com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          bitField0_ |= 0x00000001;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasBoid()) {
          setBoid(other.getBoid());
        }
        if (other.hasDestination()) {
          bitField0_ |= 0x00000004;
          destination_ = other.destination_;
          onChanged();
        }
        if (other.hasSecurityCode()) {
          bitField0_ |= 0x00000008;
          securityCode_ = other.securityCode_;
          onChanged();
        }
        if (other.hasExch()) {
          bitField0_ |= 0x00000010;
          exch_ = other.exch_;
          onChanged();
        }
        if (other.hasSecurityType()) {
          bitField0_ |= 0x00000020;
          securityType_ = other.securityType_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000040;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasOpen()) {
          setOpen(other.getOpen());
        }
        if (other.hasHigh()) {
          setHigh(other.getHigh());
        }
        if (other.hasLow()) {
          setLow(other.getLow());
        }
        if (other.hasClose()) {
          setClose(other.getClose());
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        if (other.hasChange()) {
          setChange(other.getChange());
        }
        if (other.hasPreClose()) {
          setPreClose(other.getPreClose());
        }
        if (other.hasPctChg()) {
          setPctChg(other.getPctChg());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 1;</code>
       * @return Whether the uuid field is set.
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string uuid = 1;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }

      private long boid_ ;
      /**
       * <code>optional sint64 boid = 2;</code>
       * @return Whether the boid field is set.
       */
      public boolean hasBoid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       * @return The boid.
       */
      public long getBoid() {
        return boid_;
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       * @param value The boid to set.
       * @return This builder for chaining.
       */
      public Builder setBoid(long value) {
        bitField0_ |= 0x00000002;
        boid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        boid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object destination_ = "";
      /**
       * <code>optional string destination = 3;</code>
       * @return Whether the destination field is set.
       */
      public boolean hasDestination() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string destination = 3;</code>
       * @return The destination.
       */
      public java.lang.String getDestination() {
        java.lang.Object ref = destination_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destination_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string destination = 3;</code>
       * @return The bytes for destination.
       */
      public com.google.protobuf.ByteString
          getDestinationBytes() {
        java.lang.Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destination = 3;</code>
       * @param value The destination to set.
       * @return This builder for chaining.
       */
      public Builder setDestination(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestination() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destination_ = getDefaultInstance().getDestination();
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 3;</code>
       * @param value The bytes for destination to set.
       * @return This builder for chaining.
       */
      public Builder setDestinationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destination_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object securityCode_ = "";
      /**
       * <code>optional string security_code = 4;</code>
       * @return Whether the securityCode field is set.
       */
      public boolean hasSecurityCode() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string security_code = 4;</code>
       * @return The securityCode.
       */
      public java.lang.String getSecurityCode() {
        java.lang.Object ref = securityCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            securityCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string security_code = 4;</code>
       * @return The bytes for securityCode.
       */
      public com.google.protobuf.ByteString
          getSecurityCodeBytes() {
        java.lang.Object ref = securityCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string security_code = 4;</code>
       * @param value The securityCode to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        securityCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string security_code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        securityCode_ = getDefaultInstance().getSecurityCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string security_code = 4;</code>
       * @param value The bytes for securityCode to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        securityCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exch_ = "";
      /**
       * <code>optional string exch = 5;</code>
       * @return Whether the exch field is set.
       */
      public boolean hasExch() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string exch = 5;</code>
       * @return The exch.
       */
      public java.lang.String getExch() {
        java.lang.Object ref = exch_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exch_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exch = 5;</code>
       * @return The bytes for exch.
       */
      public com.google.protobuf.ByteString
          getExchBytes() {
        java.lang.Object ref = exch_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exch_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exch = 5;</code>
       * @param value The exch to set.
       * @return This builder for chaining.
       */
      public Builder setExch(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exch = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExch() {
        bitField0_ = (bitField0_ & ~0x00000010);
        exch_ = getDefaultInstance().getExch();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exch = 5;</code>
       * @param value The bytes for exch to set.
       * @return This builder for chaining.
       */
      public Builder setExchBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exch_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object securityType_ = "";
      /**
       * <code>optional string security_type = 6;</code>
       * @return Whether the securityType field is set.
       */
      public boolean hasSecurityType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string security_type = 6;</code>
       * @return The securityType.
       */
      public java.lang.String getSecurityType() {
        java.lang.Object ref = securityType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            securityType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string security_type = 6;</code>
       * @return The bytes for securityType.
       */
      public com.google.protobuf.ByteString
          getSecurityTypeBytes() {
        java.lang.Object ref = securityType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string security_type = 6;</code>
       * @param value The securityType to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        securityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string security_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        securityType_ = getDefaultInstance().getSecurityType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string security_type = 6;</code>
       * @param value The bytes for securityType to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        securityType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>optional string date = 7;</code>
       * @return Whether the date field is set.
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string date = 7;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string date = 7;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string date = 7;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000040);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 7;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        date_ = value;
        onChanged();
        return this;
      }

      private double open_ ;
      /**
       * <code>optional double open = 8;</code>
       * @return Whether the open field is set.
       */
      public boolean hasOpen() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional double open = 8;</code>
       * @return The open.
       */
      public double getOpen() {
        return open_;
      }
      /**
       * <code>optional double open = 8;</code>
       * @param value The open to set.
       * @return This builder for chaining.
       */
      public Builder setOpen(double value) {
        bitField0_ |= 0x00000080;
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double open = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpen() {
        bitField0_ = (bitField0_ & ~0x00000080);
        open_ = 0D;
        onChanged();
        return this;
      }

      private double high_ ;
      /**
       * <code>optional double high = 9;</code>
       * @return Whether the high field is set.
       */
      public boolean hasHigh() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional double high = 9;</code>
       * @return The high.
       */
      public double getHigh() {
        return high_;
      }
      /**
       * <code>optional double high = 9;</code>
       * @param value The high to set.
       * @return This builder for chaining.
       */
      public Builder setHigh(double value) {
        bitField0_ |= 0x00000100;
        high_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double high = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearHigh() {
        bitField0_ = (bitField0_ & ~0x00000100);
        high_ = 0D;
        onChanged();
        return this;
      }

      private double low_ ;
      /**
       * <code>optional double low = 10;</code>
       * @return Whether the low field is set.
       */
      public boolean hasLow() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional double low = 10;</code>
       * @return The low.
       */
      public double getLow() {
        return low_;
      }
      /**
       * <code>optional double low = 10;</code>
       * @param value The low to set.
       * @return This builder for chaining.
       */
      public Builder setLow(double value) {
        bitField0_ |= 0x00000200;
        low_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double low = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearLow() {
        bitField0_ = (bitField0_ & ~0x00000200);
        low_ = 0D;
        onChanged();
        return this;
      }

      private double close_ ;
      /**
       * <code>optional double close = 11;</code>
       * @return Whether the close field is set.
       */
      public boolean hasClose() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional double close = 11;</code>
       * @return The close.
       */
      public double getClose() {
        return close_;
      }
      /**
       * <code>optional double close = 11;</code>
       * @param value The close to set.
       * @return This builder for chaining.
       */
      public Builder setClose(double value) {
        bitField0_ |= 0x00000400;
        close_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double close = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearClose() {
        bitField0_ = (bitField0_ & ~0x00000400);
        close_ = 0D;
        onChanged();
        return this;
      }

      private long volume_ ;
      /**
       * <code>optional sint64 volume = 12;</code>
       * @return Whether the volume field is set.
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional sint64 volume = 12;</code>
       * @return The volume.
       */
      public long getVolume() {
        return volume_;
      }
      /**
       * <code>optional sint64 volume = 12;</code>
       * @param value The volume to set.
       * @return This builder for chaining.
       */
      public Builder setVolume(long value) {
        bitField0_ |= 0x00000800;
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 volume = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000800);
        volume_ = 0L;
        onChanged();
        return this;
      }

      private double change_ ;
      /**
       * <code>optional double change = 13;</code>
       * @return Whether the change field is set.
       */
      public boolean hasChange() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <code>optional double change = 13;</code>
       * @return The change.
       */
      public double getChange() {
        return change_;
      }
      /**
       * <code>optional double change = 13;</code>
       * @param value The change to set.
       * @return This builder for chaining.
       */
      public Builder setChange(double value) {
        bitField0_ |= 0x00001000;
        change_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double change = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearChange() {
        bitField0_ = (bitField0_ & ~0x00001000);
        change_ = 0D;
        onChanged();
        return this;
      }

      private double preClose_ ;
      /**
       * <code>optional double pre_close = 14;</code>
       * @return Whether the preClose field is set.
       */
      public boolean hasPreClose() {
        return ((bitField0_ & 0x00002000) != 0);
      }
      /**
       * <code>optional double pre_close = 14;</code>
       * @return The preClose.
       */
      public double getPreClose() {
        return preClose_;
      }
      /**
       * <code>optional double pre_close = 14;</code>
       * @param value The preClose to set.
       * @return This builder for chaining.
       */
      public Builder setPreClose(double value) {
        bitField0_ |= 0x00002000;
        preClose_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double pre_close = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreClose() {
        bitField0_ = (bitField0_ & ~0x00002000);
        preClose_ = 0D;
        onChanged();
        return this;
      }

      private double pctChg_ ;
      /**
       * <code>optional double pct_chg = 15;</code>
       * @return Whether the pctChg field is set.
       */
      public boolean hasPctChg() {
        return ((bitField0_ & 0x00004000) != 0);
      }
      /**
       * <code>optional double pct_chg = 15;</code>
       * @return The pctChg.
       */
      public double getPctChg() {
        return pctChg_;
      }
      /**
       * <code>optional double pct_chg = 15;</code>
       * @param value The pctChg to set.
       * @return This builder for chaining.
       */
      public Builder setPctChg(double value) {
        bitField0_ |= 0x00004000;
        pctChg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double pct_chg = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearPctChg() {
        bitField0_ = (bitField0_ & ~0x00004000);
        pctChg_ = 0D;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>optional double amount = 16;</code>
       * @return Whether the amount field is set.
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00008000) != 0);
      }
      /**
       * <code>optional double amount = 16;</code>
       * @return The amount.
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>optional double amount = 16;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        bitField0_ |= 0x00008000;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double amount = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00008000);
        amount_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MdBarDataBO)
    }

    // @@protoc_insertion_point(class_scope:MdBarDataBO)
    private static final com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO();
    }

    public static com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MdBarDataBO>
        PARSER = new com.google.protobuf.AbstractParser<MdBarDataBO>() {
      @java.lang.Override
      public MdBarDataBO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MdBarDataBO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MdBarDataBO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MdBarDataBO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.purefun.fams.md.pro.MdBarDataBO_PRO.MdBarDataBO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MdBarDataBO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MdBarDataBO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MdBarDataBO.proto\032\031google/protobuf/any" +
      ".proto\"\224\002\n\013MdBarDataBO\022\014\n\004uuid\030\001 \001(\t\022\014\n\004" +
      "boid\030\002 \001(\022\022\023\n\013destination\030\003 \001(\t\022\025\n\rsecur" +
      "ity_code\030\004 \001(\t\022\014\n\004exch\030\005 \001(\t\022\025\n\rsecurity" +
      "_type\030\006 \001(\t\022\014\n\004date\030\007 \001(\t\022\014\n\004open\030\010 \001(\001\022" +
      "\014\n\004high\030\t \001(\001\022\013\n\003low\030\n \001(\001\022\r\n\005close\030\013 \001(" +
      "\001\022\016\n\006volume\030\014 \001(\022\022\016\n\006change\030\r \001(\001\022\021\n\tpre" +
      "_close\030\016 \001(\001\022\017\n\007pct_chg\030\017 \001(\001\022\016\n\006amount\030" +
      "\020 \001(\001B*\n\027com.purefun.fams.md.proB\017MdBarD" +
      "ataBO_PRO"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_MdBarDataBO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MdBarDataBO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MdBarDataBO_descriptor,
        new java.lang.String[] { "Uuid", "Boid", "Destination", "SecurityCode", "Exch", "SecurityType", "Date", "Open", "High", "Low", "Close", "Volume", "Change", "PreClose", "PctChg", "Amount", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
