// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MdStockSnapshotBO.proto

package com.purefun.fams.md.pro;

public final class MdStockSnapshotBO_PRO {
  private MdStockSnapshotBO_PRO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MdStockSnapshotBOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MdStockSnapshotBO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>sint64 boid = 2;</code>
     * @return The boid.
     */
    long getBoid();

    /**
     * <code>string destination = 3;</code>
     * @return The destination.
     */
    java.lang.String getDestination();
    /**
     * <code>string destination = 3;</code>
     * @return The bytes for destination.
     */
    com.google.protobuf.ByteString
        getDestinationBytes();

    /**
     * <code>string security_code = 4;</code>
     * @return The securityCode.
     */
    java.lang.String getSecurityCode();
    /**
     * <code>string security_code = 4;</code>
     * @return The bytes for securityCode.
     */
    com.google.protobuf.ByteString
        getSecurityCodeBytes();

    /**
     * <code>string exch = 5;</code>
     * @return The exch.
     */
    java.lang.String getExch();
    /**
     * <code>string exch = 5;</code>
     * @return The bytes for exch.
     */
    com.google.protobuf.ByteString
        getExchBytes();

    /**
     * <code>string security_type = 6;</code>
     * @return The securityType.
     */
    java.lang.String getSecurityType();
    /**
     * <code>string security_type = 6;</code>
     * @return The bytes for securityType.
     */
    com.google.protobuf.ByteString
        getSecurityTypeBytes();

    /**
     * <code>string cnName = 7;</code>
     * @return The cnName.
     */
    java.lang.String getCnName();
    /**
     * <code>string cnName = 7;</code>
     * @return The bytes for cnName.
     */
    com.google.protobuf.ByteString
        getCnNameBytes();

    /**
     * <code>string dateTime = 8;</code>
     * @return The dateTime.
     */
    java.lang.String getDateTime();
    /**
     * <code>string dateTime = 8;</code>
     * @return The bytes for dateTime.
     */
    com.google.protobuf.ByteString
        getDateTimeBytes();

    /**
     * <code>double open = 9;</code>
     * @return The open.
     */
    double getOpen();

    /**
     * <code>double preClose = 10;</code>
     * @return The preClose.
     */
    double getPreClose();

    /**
     * <code>double lastPrice = 11;</code>
     * @return The lastPrice.
     */
    double getLastPrice();

    /**
     * <code>double high = 12;</code>
     * @return The high.
     */
    double getHigh();

    /**
     * <code>double low = 13;</code>
     * @return The low.
     */
    double getLow();

    /**
     * <code>double change = 14;</code>
     * @return The change.
     */
    double getChange();

    /**
     * <code>double changePer = 15;</code>
     * @return The changePer.
     */
    double getChangePer();

    /**
     * <code>string buyPriceList = 16;</code>
     * @return The buyPriceList.
     */
    java.lang.String getBuyPriceList();
    /**
     * <code>string buyPriceList = 16;</code>
     * @return The bytes for buyPriceList.
     */
    com.google.protobuf.ByteString
        getBuyPriceListBytes();

    /**
     * <code>string buyQtyList = 17;</code>
     * @return The buyQtyList.
     */
    java.lang.String getBuyQtyList();
    /**
     * <code>string buyQtyList = 17;</code>
     * @return The bytes for buyQtyList.
     */
    com.google.protobuf.ByteString
        getBuyQtyListBytes();

    /**
     * <code>string sellPriceList = 18;</code>
     * @return The sellPriceList.
     */
    java.lang.String getSellPriceList();
    /**
     * <code>string sellPriceList = 18;</code>
     * @return The bytes for sellPriceList.
     */
    com.google.protobuf.ByteString
        getSellPriceListBytes();

    /**
     * <code>string sellQtyList = 19;</code>
     * @return The sellQtyList.
     */
    java.lang.String getSellQtyList();
    /**
     * <code>string sellQtyList = 19;</code>
     * @return The bytes for sellQtyList.
     */
    com.google.protobuf.ByteString
        getSellQtyListBytes();

    /**
     * <code>sint64 totalVolume = 20;</code>
     * @return The totalVolume.
     */
    long getTotalVolume();

    /**
     * <code>double totalAmont = 21;</code>
     * @return The totalAmont.
     */
    double getTotalAmont();
  }
  /**
   * Protobuf type {@code MdStockSnapshotBO}
   */
  public  static final class MdStockSnapshotBO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MdStockSnapshotBO)
      MdStockSnapshotBOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MdStockSnapshotBO.newBuilder() to construct.
    private MdStockSnapshotBO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MdStockSnapshotBO() {
      uuid_ = "";
      destination_ = "";
      securityCode_ = "";
      exch_ = "";
      securityType_ = "";
      cnName_ = "";
      dateTime_ = "";
      buyPriceList_ = "";
      buyQtyList_ = "";
      sellPriceList_ = "";
      sellQtyList_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MdStockSnapshotBO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MdStockSnapshotBO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 16: {

              boid_ = input.readSInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              destination_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              securityCode_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              exch_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              securityType_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              cnName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              dateTime_ = s;
              break;
            }
            case 73: {

              open_ = input.readDouble();
              break;
            }
            case 81: {

              preClose_ = input.readDouble();
              break;
            }
            case 89: {

              lastPrice_ = input.readDouble();
              break;
            }
            case 97: {

              high_ = input.readDouble();
              break;
            }
            case 105: {

              low_ = input.readDouble();
              break;
            }
            case 113: {

              change_ = input.readDouble();
              break;
            }
            case 121: {

              changePer_ = input.readDouble();
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              buyPriceList_ = s;
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              buyQtyList_ = s;
              break;
            }
            case 146: {
              java.lang.String s = input.readStringRequireUtf8();

              sellPriceList_ = s;
              break;
            }
            case 154: {
              java.lang.String s = input.readStringRequireUtf8();

              sellQtyList_ = s;
              break;
            }
            case 160: {

              totalVolume_ = input.readSInt64();
              break;
            }
            case 169: {

              totalAmont_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.internal_static_MdStockSnapshotBO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.internal_static_MdStockSnapshotBO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO.class, com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOID_FIELD_NUMBER = 2;
    private long boid_;
    /**
     * <code>sint64 boid = 2;</code>
     * @return The boid.
     */
    public long getBoid() {
      return boid_;
    }

    public static final int DESTINATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object destination_;
    /**
     * <code>string destination = 3;</code>
     * @return The destination.
     */
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destination_ = s;
        return s;
      }
    }
    /**
     * <code>string destination = 3;</code>
     * @return The bytes for destination.
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECURITY_CODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object securityCode_;
    /**
     * <code>string security_code = 4;</code>
     * @return The securityCode.
     */
    public java.lang.String getSecurityCode() {
      java.lang.Object ref = securityCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityCode_ = s;
        return s;
      }
    }
    /**
     * <code>string security_code = 4;</code>
     * @return The bytes for securityCode.
     */
    public com.google.protobuf.ByteString
        getSecurityCodeBytes() {
      java.lang.Object ref = securityCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCH_FIELD_NUMBER = 5;
    private volatile java.lang.Object exch_;
    /**
     * <code>string exch = 5;</code>
     * @return The exch.
     */
    public java.lang.String getExch() {
      java.lang.Object ref = exch_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exch_ = s;
        return s;
      }
    }
    /**
     * <code>string exch = 5;</code>
     * @return The bytes for exch.
     */
    public com.google.protobuf.ByteString
        getExchBytes() {
      java.lang.Object ref = exch_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECURITY_TYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object securityType_;
    /**
     * <code>string security_type = 6;</code>
     * @return The securityType.
     */
    public java.lang.String getSecurityType() {
      java.lang.Object ref = securityType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityType_ = s;
        return s;
      }
    }
    /**
     * <code>string security_type = 6;</code>
     * @return The bytes for securityType.
     */
    public com.google.protobuf.ByteString
        getSecurityTypeBytes() {
      java.lang.Object ref = securityType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CNNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object cnName_;
    /**
     * <code>string cnName = 7;</code>
     * @return The cnName.
     */
    public java.lang.String getCnName() {
      java.lang.Object ref = cnName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cnName_ = s;
        return s;
      }
    }
    /**
     * <code>string cnName = 7;</code>
     * @return The bytes for cnName.
     */
    public com.google.protobuf.ByteString
        getCnNameBytes() {
      java.lang.Object ref = cnName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cnName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATETIME_FIELD_NUMBER = 8;
    private volatile java.lang.Object dateTime_;
    /**
     * <code>string dateTime = 8;</code>
     * @return The dateTime.
     */
    public java.lang.String getDateTime() {
      java.lang.Object ref = dateTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateTime_ = s;
        return s;
      }
    }
    /**
     * <code>string dateTime = 8;</code>
     * @return The bytes for dateTime.
     */
    public com.google.protobuf.ByteString
        getDateTimeBytes() {
      java.lang.Object ref = dateTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPEN_FIELD_NUMBER = 9;
    private double open_;
    /**
     * <code>double open = 9;</code>
     * @return The open.
     */
    public double getOpen() {
      return open_;
    }

    public static final int PRECLOSE_FIELD_NUMBER = 10;
    private double preClose_;
    /**
     * <code>double preClose = 10;</code>
     * @return The preClose.
     */
    public double getPreClose() {
      return preClose_;
    }

    public static final int LASTPRICE_FIELD_NUMBER = 11;
    private double lastPrice_;
    /**
     * <code>double lastPrice = 11;</code>
     * @return The lastPrice.
     */
    public double getLastPrice() {
      return lastPrice_;
    }

    public static final int HIGH_FIELD_NUMBER = 12;
    private double high_;
    /**
     * <code>double high = 12;</code>
     * @return The high.
     */
    public double getHigh() {
      return high_;
    }

    public static final int LOW_FIELD_NUMBER = 13;
    private double low_;
    /**
     * <code>double low = 13;</code>
     * @return The low.
     */
    public double getLow() {
      return low_;
    }

    public static final int CHANGE_FIELD_NUMBER = 14;
    private double change_;
    /**
     * <code>double change = 14;</code>
     * @return The change.
     */
    public double getChange() {
      return change_;
    }

    public static final int CHANGEPER_FIELD_NUMBER = 15;
    private double changePer_;
    /**
     * <code>double changePer = 15;</code>
     * @return The changePer.
     */
    public double getChangePer() {
      return changePer_;
    }

    public static final int BUYPRICELIST_FIELD_NUMBER = 16;
    private volatile java.lang.Object buyPriceList_;
    /**
     * <code>string buyPriceList = 16;</code>
     * @return The buyPriceList.
     */
    public java.lang.String getBuyPriceList() {
      java.lang.Object ref = buyPriceList_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buyPriceList_ = s;
        return s;
      }
    }
    /**
     * <code>string buyPriceList = 16;</code>
     * @return The bytes for buyPriceList.
     */
    public com.google.protobuf.ByteString
        getBuyPriceListBytes() {
      java.lang.Object ref = buyPriceList_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buyPriceList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUYQTYLIST_FIELD_NUMBER = 17;
    private volatile java.lang.Object buyQtyList_;
    /**
     * <code>string buyQtyList = 17;</code>
     * @return The buyQtyList.
     */
    public java.lang.String getBuyQtyList() {
      java.lang.Object ref = buyQtyList_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buyQtyList_ = s;
        return s;
      }
    }
    /**
     * <code>string buyQtyList = 17;</code>
     * @return The bytes for buyQtyList.
     */
    public com.google.protobuf.ByteString
        getBuyQtyListBytes() {
      java.lang.Object ref = buyQtyList_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buyQtyList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SELLPRICELIST_FIELD_NUMBER = 18;
    private volatile java.lang.Object sellPriceList_;
    /**
     * <code>string sellPriceList = 18;</code>
     * @return The sellPriceList.
     */
    public java.lang.String getSellPriceList() {
      java.lang.Object ref = sellPriceList_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sellPriceList_ = s;
        return s;
      }
    }
    /**
     * <code>string sellPriceList = 18;</code>
     * @return The bytes for sellPriceList.
     */
    public com.google.protobuf.ByteString
        getSellPriceListBytes() {
      java.lang.Object ref = sellPriceList_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sellPriceList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SELLQTYLIST_FIELD_NUMBER = 19;
    private volatile java.lang.Object sellQtyList_;
    /**
     * <code>string sellQtyList = 19;</code>
     * @return The sellQtyList.
     */
    public java.lang.String getSellQtyList() {
      java.lang.Object ref = sellQtyList_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sellQtyList_ = s;
        return s;
      }
    }
    /**
     * <code>string sellQtyList = 19;</code>
     * @return The bytes for sellQtyList.
     */
    public com.google.protobuf.ByteString
        getSellQtyListBytes() {
      java.lang.Object ref = sellQtyList_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sellQtyList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTALVOLUME_FIELD_NUMBER = 20;
    private long totalVolume_;
    /**
     * <code>sint64 totalVolume = 20;</code>
     * @return The totalVolume.
     */
    public long getTotalVolume() {
      return totalVolume_;
    }

    public static final int TOTALAMONT_FIELD_NUMBER = 21;
    private double totalAmont_;
    /**
     * <code>double totalAmont = 21;</code>
     * @return The totalAmont.
     */
    public double getTotalAmont() {
      return totalAmont_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (boid_ != 0L) {
        output.writeSInt64(2, boid_);
      }
      if (!getDestinationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, destination_);
      }
      if (!getSecurityCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, securityCode_);
      }
      if (!getExchBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, exch_);
      }
      if (!getSecurityTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, securityType_);
      }
      if (!getCnNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, cnName_);
      }
      if (!getDateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, dateTime_);
      }
      if (open_ != 0D) {
        output.writeDouble(9, open_);
      }
      if (preClose_ != 0D) {
        output.writeDouble(10, preClose_);
      }
      if (lastPrice_ != 0D) {
        output.writeDouble(11, lastPrice_);
      }
      if (high_ != 0D) {
        output.writeDouble(12, high_);
      }
      if (low_ != 0D) {
        output.writeDouble(13, low_);
      }
      if (change_ != 0D) {
        output.writeDouble(14, change_);
      }
      if (changePer_ != 0D) {
        output.writeDouble(15, changePer_);
      }
      if (!getBuyPriceListBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, buyPriceList_);
      }
      if (!getBuyQtyListBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, buyQtyList_);
      }
      if (!getSellPriceListBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, sellPriceList_);
      }
      if (!getSellQtyListBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 19, sellQtyList_);
      }
      if (totalVolume_ != 0L) {
        output.writeSInt64(20, totalVolume_);
      }
      if (totalAmont_ != 0D) {
        output.writeDouble(21, totalAmont_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (boid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, boid_);
      }
      if (!getDestinationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, destination_);
      }
      if (!getSecurityCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, securityCode_);
      }
      if (!getExchBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, exch_);
      }
      if (!getSecurityTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, securityType_);
      }
      if (!getCnNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, cnName_);
      }
      if (!getDateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, dateTime_);
      }
      if (open_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, open_);
      }
      if (preClose_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, preClose_);
      }
      if (lastPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, lastPrice_);
      }
      if (high_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, high_);
      }
      if (low_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, low_);
      }
      if (change_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, change_);
      }
      if (changePer_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(15, changePer_);
      }
      if (!getBuyPriceListBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, buyPriceList_);
      }
      if (!getBuyQtyListBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, buyQtyList_);
      }
      if (!getSellPriceListBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, sellPriceList_);
      }
      if (!getSellQtyListBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, sellQtyList_);
      }
      if (totalVolume_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(20, totalVolume_);
      }
      if (totalAmont_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(21, totalAmont_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO)) {
        return super.equals(obj);
      }
      com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO other = (com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO) obj;

      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (getBoid()
          != other.getBoid()) return false;
      if (!getDestination()
          .equals(other.getDestination())) return false;
      if (!getSecurityCode()
          .equals(other.getSecurityCode())) return false;
      if (!getExch()
          .equals(other.getExch())) return false;
      if (!getSecurityType()
          .equals(other.getSecurityType())) return false;
      if (!getCnName()
          .equals(other.getCnName())) return false;
      if (!getDateTime()
          .equals(other.getDateTime())) return false;
      if (java.lang.Double.doubleToLongBits(getOpen())
          != java.lang.Double.doubleToLongBits(
              other.getOpen())) return false;
      if (java.lang.Double.doubleToLongBits(getPreClose())
          != java.lang.Double.doubleToLongBits(
              other.getPreClose())) return false;
      if (java.lang.Double.doubleToLongBits(getLastPrice())
          != java.lang.Double.doubleToLongBits(
              other.getLastPrice())) return false;
      if (java.lang.Double.doubleToLongBits(getHigh())
          != java.lang.Double.doubleToLongBits(
              other.getHigh())) return false;
      if (java.lang.Double.doubleToLongBits(getLow())
          != java.lang.Double.doubleToLongBits(
              other.getLow())) return false;
      if (java.lang.Double.doubleToLongBits(getChange())
          != java.lang.Double.doubleToLongBits(
              other.getChange())) return false;
      if (java.lang.Double.doubleToLongBits(getChangePer())
          != java.lang.Double.doubleToLongBits(
              other.getChangePer())) return false;
      if (!getBuyPriceList()
          .equals(other.getBuyPriceList())) return false;
      if (!getBuyQtyList()
          .equals(other.getBuyQtyList())) return false;
      if (!getSellPriceList()
          .equals(other.getSellPriceList())) return false;
      if (!getSellQtyList()
          .equals(other.getSellQtyList())) return false;
      if (getTotalVolume()
          != other.getTotalVolume()) return false;
      if (java.lang.Double.doubleToLongBits(getTotalAmont())
          != java.lang.Double.doubleToLongBits(
              other.getTotalAmont())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + BOID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBoid());
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + getDestination().hashCode();
      hash = (37 * hash) + SECURITY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityCode().hashCode();
      hash = (37 * hash) + EXCH_FIELD_NUMBER;
      hash = (53 * hash) + getExch().hashCode();
      hash = (37 * hash) + SECURITY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityType().hashCode();
      hash = (37 * hash) + CNNAME_FIELD_NUMBER;
      hash = (53 * hash) + getCnName().hashCode();
      hash = (37 * hash) + DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getDateTime().hashCode();
      hash = (37 * hash) + OPEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOpen()));
      hash = (37 * hash) + PRECLOSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPreClose()));
      hash = (37 * hash) + LASTPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLastPrice()));
      hash = (37 * hash) + HIGH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHigh()));
      hash = (37 * hash) + LOW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLow()));
      hash = (37 * hash) + CHANGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getChange()));
      hash = (37 * hash) + CHANGEPER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getChangePer()));
      hash = (37 * hash) + BUYPRICELIST_FIELD_NUMBER;
      hash = (53 * hash) + getBuyPriceList().hashCode();
      hash = (37 * hash) + BUYQTYLIST_FIELD_NUMBER;
      hash = (53 * hash) + getBuyQtyList().hashCode();
      hash = (37 * hash) + SELLPRICELIST_FIELD_NUMBER;
      hash = (53 * hash) + getSellPriceList().hashCode();
      hash = (37 * hash) + SELLQTYLIST_FIELD_NUMBER;
      hash = (53 * hash) + getSellQtyList().hashCode();
      hash = (37 * hash) + TOTALVOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalVolume());
      hash = (37 * hash) + TOTALAMONT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTotalAmont()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MdStockSnapshotBO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MdStockSnapshotBO)
        com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.internal_static_MdStockSnapshotBO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.internal_static_MdStockSnapshotBO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO.class, com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO.Builder.class);
      }

      // Construct using com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uuid_ = "";

        boid_ = 0L;

        destination_ = "";

        securityCode_ = "";

        exch_ = "";

        securityType_ = "";

        cnName_ = "";

        dateTime_ = "";

        open_ = 0D;

        preClose_ = 0D;

        lastPrice_ = 0D;

        high_ = 0D;

        low_ = 0D;

        change_ = 0D;

        changePer_ = 0D;

        buyPriceList_ = "";

        buyQtyList_ = "";

        sellPriceList_ = "";

        sellQtyList_ = "";

        totalVolume_ = 0L;

        totalAmont_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.internal_static_MdStockSnapshotBO_descriptor;
      }

      @java.lang.Override
      public com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO getDefaultInstanceForType() {
        return com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO.getDefaultInstance();
      }

      @java.lang.Override
      public com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO build() {
        com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO buildPartial() {
        com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO result = new com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO(this);
        result.uuid_ = uuid_;
        result.boid_ = boid_;
        result.destination_ = destination_;
        result.securityCode_ = securityCode_;
        result.exch_ = exch_;
        result.securityType_ = securityType_;
        result.cnName_ = cnName_;
        result.dateTime_ = dateTime_;
        result.open_ = open_;
        result.preClose_ = preClose_;
        result.lastPrice_ = lastPrice_;
        result.high_ = high_;
        result.low_ = low_;
        result.change_ = change_;
        result.changePer_ = changePer_;
        result.buyPriceList_ = buyPriceList_;
        result.buyQtyList_ = buyQtyList_;
        result.sellPriceList_ = sellPriceList_;
        result.sellQtyList_ = sellQtyList_;
        result.totalVolume_ = totalVolume_;
        result.totalAmont_ = totalAmont_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO) {
          return mergeFrom((com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO other) {
        if (other == com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.getBoid() != 0L) {
          setBoid(other.getBoid());
        }
        if (!other.getDestination().isEmpty()) {
          destination_ = other.destination_;
          onChanged();
        }
        if (!other.getSecurityCode().isEmpty()) {
          securityCode_ = other.securityCode_;
          onChanged();
        }
        if (!other.getExch().isEmpty()) {
          exch_ = other.exch_;
          onChanged();
        }
        if (!other.getSecurityType().isEmpty()) {
          securityType_ = other.securityType_;
          onChanged();
        }
        if (!other.getCnName().isEmpty()) {
          cnName_ = other.cnName_;
          onChanged();
        }
        if (!other.getDateTime().isEmpty()) {
          dateTime_ = other.dateTime_;
          onChanged();
        }
        if (other.getOpen() != 0D) {
          setOpen(other.getOpen());
        }
        if (other.getPreClose() != 0D) {
          setPreClose(other.getPreClose());
        }
        if (other.getLastPrice() != 0D) {
          setLastPrice(other.getLastPrice());
        }
        if (other.getHigh() != 0D) {
          setHigh(other.getHigh());
        }
        if (other.getLow() != 0D) {
          setLow(other.getLow());
        }
        if (other.getChange() != 0D) {
          setChange(other.getChange());
        }
        if (other.getChangePer() != 0D) {
          setChangePer(other.getChangePer());
        }
        if (!other.getBuyPriceList().isEmpty()) {
          buyPriceList_ = other.buyPriceList_;
          onChanged();
        }
        if (!other.getBuyQtyList().isEmpty()) {
          buyQtyList_ = other.buyQtyList_;
          onChanged();
        }
        if (!other.getSellPriceList().isEmpty()) {
          sellPriceList_ = other.sellPriceList_;
          onChanged();
        }
        if (!other.getSellQtyList().isEmpty()) {
          sellQtyList_ = other.sellQtyList_;
          onChanged();
        }
        if (other.getTotalVolume() != 0L) {
          setTotalVolume(other.getTotalVolume());
        }
        if (other.getTotalAmont() != 0D) {
          setTotalAmont(other.getTotalAmont());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private long boid_ ;
      /**
       * <code>sint64 boid = 2;</code>
       * @return The boid.
       */
      public long getBoid() {
        return boid_;
      }
      /**
       * <code>sint64 boid = 2;</code>
       * @param value The boid to set.
       * @return This builder for chaining.
       */
      public Builder setBoid(long value) {
        
        boid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 boid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoid() {
        
        boid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object destination_ = "";
      /**
       * <code>string destination = 3;</code>
       * @return The destination.
       */
      public java.lang.String getDestination() {
        java.lang.Object ref = destination_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destination_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string destination = 3;</code>
       * @return The bytes for destination.
       */
      public com.google.protobuf.ByteString
          getDestinationBytes() {
        java.lang.Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destination = 3;</code>
       * @param value The destination to set.
       * @return This builder for chaining.
       */
      public Builder setDestination(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string destination = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestination() {
        
        destination_ = getDefaultInstance().getDestination();
        onChanged();
        return this;
      }
      /**
       * <code>string destination = 3;</code>
       * @param value The bytes for destination to set.
       * @return This builder for chaining.
       */
      public Builder setDestinationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destination_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object securityCode_ = "";
      /**
       * <code>string security_code = 4;</code>
       * @return The securityCode.
       */
      public java.lang.String getSecurityCode() {
        java.lang.Object ref = securityCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          securityCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string security_code = 4;</code>
       * @return The bytes for securityCode.
       */
      public com.google.protobuf.ByteString
          getSecurityCodeBytes() {
        java.lang.Object ref = securityCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string security_code = 4;</code>
       * @param value The securityCode to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        securityCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string security_code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityCode() {
        
        securityCode_ = getDefaultInstance().getSecurityCode();
        onChanged();
        return this;
      }
      /**
       * <code>string security_code = 4;</code>
       * @param value The bytes for securityCode to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        securityCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exch_ = "";
      /**
       * <code>string exch = 5;</code>
       * @return The exch.
       */
      public java.lang.String getExch() {
        java.lang.Object ref = exch_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exch_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exch = 5;</code>
       * @return The bytes for exch.
       */
      public com.google.protobuf.ByteString
          getExchBytes() {
        java.lang.Object ref = exch_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exch_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exch = 5;</code>
       * @param value The exch to set.
       * @return This builder for chaining.
       */
      public Builder setExch(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exch = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExch() {
        
        exch_ = getDefaultInstance().getExch();
        onChanged();
        return this;
      }
      /**
       * <code>string exch = 5;</code>
       * @param value The bytes for exch to set.
       * @return This builder for chaining.
       */
      public Builder setExchBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exch_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object securityType_ = "";
      /**
       * <code>string security_type = 6;</code>
       * @return The securityType.
       */
      public java.lang.String getSecurityType() {
        java.lang.Object ref = securityType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          securityType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string security_type = 6;</code>
       * @return The bytes for securityType.
       */
      public com.google.protobuf.ByteString
          getSecurityTypeBytes() {
        java.lang.Object ref = securityType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string security_type = 6;</code>
       * @param value The securityType to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        securityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string security_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityType() {
        
        securityType_ = getDefaultInstance().getSecurityType();
        onChanged();
        return this;
      }
      /**
       * <code>string security_type = 6;</code>
       * @param value The bytes for securityType to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        securityType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cnName_ = "";
      /**
       * <code>string cnName = 7;</code>
       * @return The cnName.
       */
      public java.lang.String getCnName() {
        java.lang.Object ref = cnName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cnName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cnName = 7;</code>
       * @return The bytes for cnName.
       */
      public com.google.protobuf.ByteString
          getCnNameBytes() {
        java.lang.Object ref = cnName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cnName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cnName = 7;</code>
       * @param value The cnName to set.
       * @return This builder for chaining.
       */
      public Builder setCnName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cnName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cnName = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCnName() {
        
        cnName_ = getDefaultInstance().getCnName();
        onChanged();
        return this;
      }
      /**
       * <code>string cnName = 7;</code>
       * @param value The bytes for cnName to set.
       * @return This builder for chaining.
       */
      public Builder setCnNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cnName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dateTime_ = "";
      /**
       * <code>string dateTime = 8;</code>
       * @return The dateTime.
       */
      public java.lang.String getDateTime() {
        java.lang.Object ref = dateTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dateTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dateTime = 8;</code>
       * @return The bytes for dateTime.
       */
      public com.google.protobuf.ByteString
          getDateTimeBytes() {
        java.lang.Object ref = dateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dateTime = 8;</code>
       * @param value The dateTime to set.
       * @return This builder for chaining.
       */
      public Builder setDateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dateTime = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearDateTime() {
        
        dateTime_ = getDefaultInstance().getDateTime();
        onChanged();
        return this;
      }
      /**
       * <code>string dateTime = 8;</code>
       * @param value The bytes for dateTime to set.
       * @return This builder for chaining.
       */
      public Builder setDateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dateTime_ = value;
        onChanged();
        return this;
      }

      private double open_ ;
      /**
       * <code>double open = 9;</code>
       * @return The open.
       */
      public double getOpen() {
        return open_;
      }
      /**
       * <code>double open = 9;</code>
       * @param value The open to set.
       * @return This builder for chaining.
       */
      public Builder setOpen(double value) {
        
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double open = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpen() {
        
        open_ = 0D;
        onChanged();
        return this;
      }

      private double preClose_ ;
      /**
       * <code>double preClose = 10;</code>
       * @return The preClose.
       */
      public double getPreClose() {
        return preClose_;
      }
      /**
       * <code>double preClose = 10;</code>
       * @param value The preClose to set.
       * @return This builder for chaining.
       */
      public Builder setPreClose(double value) {
        
        preClose_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double preClose = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreClose() {
        
        preClose_ = 0D;
        onChanged();
        return this;
      }

      private double lastPrice_ ;
      /**
       * <code>double lastPrice = 11;</code>
       * @return The lastPrice.
       */
      public double getLastPrice() {
        return lastPrice_;
      }
      /**
       * <code>double lastPrice = 11;</code>
       * @param value The lastPrice to set.
       * @return This builder for chaining.
       */
      public Builder setLastPrice(double value) {
        
        lastPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double lastPrice = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastPrice() {
        
        lastPrice_ = 0D;
        onChanged();
        return this;
      }

      private double high_ ;
      /**
       * <code>double high = 12;</code>
       * @return The high.
       */
      public double getHigh() {
        return high_;
      }
      /**
       * <code>double high = 12;</code>
       * @param value The high to set.
       * @return This builder for chaining.
       */
      public Builder setHigh(double value) {
        
        high_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double high = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearHigh() {
        
        high_ = 0D;
        onChanged();
        return this;
      }

      private double low_ ;
      /**
       * <code>double low = 13;</code>
       * @return The low.
       */
      public double getLow() {
        return low_;
      }
      /**
       * <code>double low = 13;</code>
       * @param value The low to set.
       * @return This builder for chaining.
       */
      public Builder setLow(double value) {
        
        low_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double low = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearLow() {
        
        low_ = 0D;
        onChanged();
        return this;
      }

      private double change_ ;
      /**
       * <code>double change = 14;</code>
       * @return The change.
       */
      public double getChange() {
        return change_;
      }
      /**
       * <code>double change = 14;</code>
       * @param value The change to set.
       * @return This builder for chaining.
       */
      public Builder setChange(double value) {
        
        change_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double change = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearChange() {
        
        change_ = 0D;
        onChanged();
        return this;
      }

      private double changePer_ ;
      /**
       * <code>double changePer = 15;</code>
       * @return The changePer.
       */
      public double getChangePer() {
        return changePer_;
      }
      /**
       * <code>double changePer = 15;</code>
       * @param value The changePer to set.
       * @return This builder for chaining.
       */
      public Builder setChangePer(double value) {
        
        changePer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double changePer = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearChangePer() {
        
        changePer_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object buyPriceList_ = "";
      /**
       * <code>string buyPriceList = 16;</code>
       * @return The buyPriceList.
       */
      public java.lang.String getBuyPriceList() {
        java.lang.Object ref = buyPriceList_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buyPriceList_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string buyPriceList = 16;</code>
       * @return The bytes for buyPriceList.
       */
      public com.google.protobuf.ByteString
          getBuyPriceListBytes() {
        java.lang.Object ref = buyPriceList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buyPriceList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string buyPriceList = 16;</code>
       * @param value The buyPriceList to set.
       * @return This builder for chaining.
       */
      public Builder setBuyPriceList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buyPriceList_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string buyPriceList = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuyPriceList() {
        
        buyPriceList_ = getDefaultInstance().getBuyPriceList();
        onChanged();
        return this;
      }
      /**
       * <code>string buyPriceList = 16;</code>
       * @param value The bytes for buyPriceList to set.
       * @return This builder for chaining.
       */
      public Builder setBuyPriceListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buyPriceList_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object buyQtyList_ = "";
      /**
       * <code>string buyQtyList = 17;</code>
       * @return The buyQtyList.
       */
      public java.lang.String getBuyQtyList() {
        java.lang.Object ref = buyQtyList_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buyQtyList_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string buyQtyList = 17;</code>
       * @return The bytes for buyQtyList.
       */
      public com.google.protobuf.ByteString
          getBuyQtyListBytes() {
        java.lang.Object ref = buyQtyList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buyQtyList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string buyQtyList = 17;</code>
       * @param value The buyQtyList to set.
       * @return This builder for chaining.
       */
      public Builder setBuyQtyList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buyQtyList_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string buyQtyList = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuyQtyList() {
        
        buyQtyList_ = getDefaultInstance().getBuyQtyList();
        onChanged();
        return this;
      }
      /**
       * <code>string buyQtyList = 17;</code>
       * @param value The bytes for buyQtyList to set.
       * @return This builder for chaining.
       */
      public Builder setBuyQtyListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buyQtyList_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sellPriceList_ = "";
      /**
       * <code>string sellPriceList = 18;</code>
       * @return The sellPriceList.
       */
      public java.lang.String getSellPriceList() {
        java.lang.Object ref = sellPriceList_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sellPriceList_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sellPriceList = 18;</code>
       * @return The bytes for sellPriceList.
       */
      public com.google.protobuf.ByteString
          getSellPriceListBytes() {
        java.lang.Object ref = sellPriceList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sellPriceList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sellPriceList = 18;</code>
       * @param value The sellPriceList to set.
       * @return This builder for chaining.
       */
      public Builder setSellPriceList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sellPriceList_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sellPriceList = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearSellPriceList() {
        
        sellPriceList_ = getDefaultInstance().getSellPriceList();
        onChanged();
        return this;
      }
      /**
       * <code>string sellPriceList = 18;</code>
       * @param value The bytes for sellPriceList to set.
       * @return This builder for chaining.
       */
      public Builder setSellPriceListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sellPriceList_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sellQtyList_ = "";
      /**
       * <code>string sellQtyList = 19;</code>
       * @return The sellQtyList.
       */
      public java.lang.String getSellQtyList() {
        java.lang.Object ref = sellQtyList_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sellQtyList_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sellQtyList = 19;</code>
       * @return The bytes for sellQtyList.
       */
      public com.google.protobuf.ByteString
          getSellQtyListBytes() {
        java.lang.Object ref = sellQtyList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sellQtyList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sellQtyList = 19;</code>
       * @param value The sellQtyList to set.
       * @return This builder for chaining.
       */
      public Builder setSellQtyList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sellQtyList_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sellQtyList = 19;</code>
       * @return This builder for chaining.
       */
      public Builder clearSellQtyList() {
        
        sellQtyList_ = getDefaultInstance().getSellQtyList();
        onChanged();
        return this;
      }
      /**
       * <code>string sellQtyList = 19;</code>
       * @param value The bytes for sellQtyList to set.
       * @return This builder for chaining.
       */
      public Builder setSellQtyListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sellQtyList_ = value;
        onChanged();
        return this;
      }

      private long totalVolume_ ;
      /**
       * <code>sint64 totalVolume = 20;</code>
       * @return The totalVolume.
       */
      public long getTotalVolume() {
        return totalVolume_;
      }
      /**
       * <code>sint64 totalVolume = 20;</code>
       * @param value The totalVolume to set.
       * @return This builder for chaining.
       */
      public Builder setTotalVolume(long value) {
        
        totalVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 totalVolume = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalVolume() {
        
        totalVolume_ = 0L;
        onChanged();
        return this;
      }

      private double totalAmont_ ;
      /**
       * <code>double totalAmont = 21;</code>
       * @return The totalAmont.
       */
      public double getTotalAmont() {
        return totalAmont_;
      }
      /**
       * <code>double totalAmont = 21;</code>
       * @param value The totalAmont to set.
       * @return This builder for chaining.
       */
      public Builder setTotalAmont(double value) {
        
        totalAmont_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double totalAmont = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalAmont() {
        
        totalAmont_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MdStockSnapshotBO)
    }

    // @@protoc_insertion_point(class_scope:MdStockSnapshotBO)
    private static final com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO();
    }

    public static com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MdStockSnapshotBO>
        PARSER = new com.google.protobuf.AbstractParser<MdStockSnapshotBO>() {
      @java.lang.Override
      public MdStockSnapshotBO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MdStockSnapshotBO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MdStockSnapshotBO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MdStockSnapshotBO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.purefun.fams.md.pro.MdStockSnapshotBO_PRO.MdStockSnapshotBO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MdStockSnapshotBO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MdStockSnapshotBO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027MdStockSnapshotBO.proto\"\222\003\n\021MdStockSna" +
      "pshotBO\022\014\n\004uuid\030\001 \001(\t\022\014\n\004boid\030\002 \001(\022\022\023\n\013d" +
      "estination\030\003 \001(\t\022\025\n\rsecurity_code\030\004 \001(\t\022" +
      "\014\n\004exch\030\005 \001(\t\022\025\n\rsecurity_type\030\006 \001(\t\022\016\n\006" +
      "cnName\030\007 \001(\t\022\020\n\010dateTime\030\010 \001(\t\022\014\n\004open\030\t" +
      " \001(\001\022\020\n\010preClose\030\n \001(\001\022\021\n\tlastPrice\030\013 \001(" +
      "\001\022\014\n\004high\030\014 \001(\001\022\013\n\003low\030\r \001(\001\022\016\n\006change\030\016" +
      " \001(\001\022\021\n\tchangePer\030\017 \001(\001\022\024\n\014buyPriceList\030" +
      "\020 \001(\t\022\022\n\nbuyQtyList\030\021 \001(\t\022\025\n\rsellPriceLi" +
      "st\030\022 \001(\t\022\023\n\013sellQtyList\030\023 \001(\t\022\023\n\013totalVo" +
      "lume\030\024 \001(\022\022\022\n\ntotalAmont\030\025 \001(\001B0\n\027com.pu" +
      "refun.fams.md.proB\025MdStockSnapshotBO_PRO" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MdStockSnapshotBO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MdStockSnapshotBO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MdStockSnapshotBO_descriptor,
        new java.lang.String[] { "Uuid", "Boid", "Destination", "SecurityCode", "Exch", "SecurityType", "CnName", "DateTime", "Open", "PreClose", "LastPrice", "High", "Low", "Change", "ChangePer", "BuyPriceList", "BuyQtyList", "SellPriceList", "SellQtyList", "TotalVolume", "TotalAmont", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
