// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderBO.proto

package com.purefun.fams.trade.order.pro;

public final class OrderBO_PRO {
  private OrderBO_PRO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderBOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderBO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>sint64 boid = 2;</code>
     * @return The boid.
     */
    long getBoid();

    /**
     * <code>string account = 4;</code>
     * @return The account.
     */
    java.lang.String getAccount();
    /**
     * <code>string account = 4;</code>
     * @return The bytes for account.
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>string security_code = 5;</code>
     * @return The securityCode.
     */
    java.lang.String getSecurityCode();
    /**
     * <code>string security_code = 5;</code>
     * @return The bytes for securityCode.
     */
    com.google.protobuf.ByteString
        getSecurityCodeBytes();

    /**
     * <code>string exch = 6;</code>
     * @return The exch.
     */
    java.lang.String getExch();
    /**
     * <code>string exch = 6;</code>
     * @return The bytes for exch.
     */
    com.google.protobuf.ByteString
        getExchBytes();

    /**
     * <code>string security_type = 7;</code>
     * @return The securityType.
     */
    java.lang.String getSecurityType();
    /**
     * <code>string security_type = 7;</code>
     * @return The bytes for securityType.
     */
    com.google.protobuf.ByteString
        getSecurityTypeBytes();

    /**
     * <code>string tradeDate = 8;</code>
     * @return The tradeDate.
     */
    java.lang.String getTradeDate();
    /**
     * <code>string tradeDate = 8;</code>
     * @return The bytes for tradeDate.
     */
    com.google.protobuf.ByteString
        getTradeDateBytes();

    /**
     * <code>string orderId = 9;</code>
     * @return The orderId.
     */
    java.lang.String getOrderId();
    /**
     * <code>string orderId = 9;</code>
     * @return The bytes for orderId.
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>string orderStatus = 10;</code>
     * @return The orderStatus.
     */
    java.lang.String getOrderStatus();
    /**
     * <code>string orderStatus = 10;</code>
     * @return The bytes for orderStatus.
     */
    com.google.protobuf.ByteString
        getOrderStatusBytes();

    /**
     * <code>string orderRejectedReson = 11;</code>
     * @return The orderRejectedReson.
     */
    java.lang.String getOrderRejectedReson();
    /**
     * <code>string orderRejectedReson = 11;</code>
     * @return The bytes for orderRejectedReson.
     */
    com.google.protobuf.ByteString
        getOrderRejectedResonBytes();

    /**
     * <code>string orderType = 12;</code>
     * @return The orderType.
     */
    java.lang.String getOrderType();
    /**
     * <code>string orderType = 12;</code>
     * @return The bytes for orderType.
     */
    com.google.protobuf.ByteString
        getOrderTypeBytes();

    /**
     * <code>double orderPrice = 13;</code>
     * @return The orderPrice.
     */
    double getOrderPrice();

    /**
     * <code>sint64 orderVolume = 14;</code>
     * @return The orderVolume.
     */
    long getOrderVolume();

    /**
     * <code>string direction = 15;</code>
     * @return The direction.
     */
    java.lang.String getDirection();
    /**
     * <code>string direction = 15;</code>
     * @return The bytes for direction.
     */
    com.google.protobuf.ByteString
        getDirectionBytes();

    /**
     * <code>string execStatus = 16;</code>
     * @return The execStatus.
     */
    java.lang.String getExecStatus();
    /**
     * <code>string execStatus = 16;</code>
     * @return The bytes for execStatus.
     */
    com.google.protobuf.ByteString
        getExecStatusBytes();

    /**
     * <code>bool withdrawFlag = 17;</code>
     * @return The withdrawFlag.
     */
    boolean getWithdrawFlag();

    /**
     * <code>sint64 withdrawVolume = 18;</code>
     * @return The withdrawVolume.
     */
    long getWithdrawVolume();
  }
  /**
   * Protobuf type {@code OrderBO}
   */
  public  static final class OrderBO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OrderBO)
      OrderBOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderBO.newBuilder() to construct.
    private OrderBO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderBO() {
      uuid_ = "";
      account_ = "";
      securityCode_ = "";
      exch_ = "";
      securityType_ = "";
      tradeDate_ = "";
      orderId_ = "";
      orderStatus_ = "";
      orderRejectedReson_ = "";
      orderType_ = "";
      direction_ = "";
      execStatus_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OrderBO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderBO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 16: {

              boid_ = input.readSInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              securityCode_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              exch_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              securityType_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              tradeDate_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              orderId_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              orderStatus_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              orderRejectedReson_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              orderType_ = s;
              break;
            }
            case 105: {

              orderPrice_ = input.readDouble();
              break;
            }
            case 112: {

              orderVolume_ = input.readSInt64();
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              direction_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              execStatus_ = s;
              break;
            }
            case 136: {

              withdrawFlag_ = input.readBool();
              break;
            }
            case 144: {

              withdrawVolume_ = input.readSInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.purefun.fams.trade.order.pro.OrderBO_PRO.internal_static_OrderBO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.purefun.fams.trade.order.pro.OrderBO_PRO.internal_static_OrderBO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO.class, com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOID_FIELD_NUMBER = 2;
    private long boid_;
    /**
     * <code>sint64 boid = 2;</code>
     * @return The boid.
     */
    public long getBoid() {
      return boid_;
    }

    public static final int ACCOUNT_FIELD_NUMBER = 4;
    private volatile java.lang.Object account_;
    /**
     * <code>string account = 4;</code>
     * @return The account.
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>string account = 4;</code>
     * @return The bytes for account.
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECURITY_CODE_FIELD_NUMBER = 5;
    private volatile java.lang.Object securityCode_;
    /**
     * <code>string security_code = 5;</code>
     * @return The securityCode.
     */
    public java.lang.String getSecurityCode() {
      java.lang.Object ref = securityCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityCode_ = s;
        return s;
      }
    }
    /**
     * <code>string security_code = 5;</code>
     * @return The bytes for securityCode.
     */
    public com.google.protobuf.ByteString
        getSecurityCodeBytes() {
      java.lang.Object ref = securityCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCH_FIELD_NUMBER = 6;
    private volatile java.lang.Object exch_;
    /**
     * <code>string exch = 6;</code>
     * @return The exch.
     */
    public java.lang.String getExch() {
      java.lang.Object ref = exch_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exch_ = s;
        return s;
      }
    }
    /**
     * <code>string exch = 6;</code>
     * @return The bytes for exch.
     */
    public com.google.protobuf.ByteString
        getExchBytes() {
      java.lang.Object ref = exch_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECURITY_TYPE_FIELD_NUMBER = 7;
    private volatile java.lang.Object securityType_;
    /**
     * <code>string security_type = 7;</code>
     * @return The securityType.
     */
    public java.lang.String getSecurityType() {
      java.lang.Object ref = securityType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityType_ = s;
        return s;
      }
    }
    /**
     * <code>string security_type = 7;</code>
     * @return The bytes for securityType.
     */
    public com.google.protobuf.ByteString
        getSecurityTypeBytes() {
      java.lang.Object ref = securityType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRADEDATE_FIELD_NUMBER = 8;
    private volatile java.lang.Object tradeDate_;
    /**
     * <code>string tradeDate = 8;</code>
     * @return The tradeDate.
     */
    public java.lang.String getTradeDate() {
      java.lang.Object ref = tradeDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tradeDate_ = s;
        return s;
      }
    }
    /**
     * <code>string tradeDate = 8;</code>
     * @return The bytes for tradeDate.
     */
    public com.google.protobuf.ByteString
        getTradeDateBytes() {
      java.lang.Object ref = tradeDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tradeDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERID_FIELD_NUMBER = 9;
    private volatile java.lang.Object orderId_;
    /**
     * <code>string orderId = 9;</code>
     * @return The orderId.
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      }
    }
    /**
     * <code>string orderId = 9;</code>
     * @return The bytes for orderId.
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERSTATUS_FIELD_NUMBER = 10;
    private volatile java.lang.Object orderStatus_;
    /**
     * <code>string orderStatus = 10;</code>
     * @return The orderStatus.
     */
    public java.lang.String getOrderStatus() {
      java.lang.Object ref = orderStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string orderStatus = 10;</code>
     * @return The bytes for orderStatus.
     */
    public com.google.protobuf.ByteString
        getOrderStatusBytes() {
      java.lang.Object ref = orderStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERREJECTEDRESON_FIELD_NUMBER = 11;
    private volatile java.lang.Object orderRejectedReson_;
    /**
     * <code>string orderRejectedReson = 11;</code>
     * @return The orderRejectedReson.
     */
    public java.lang.String getOrderRejectedReson() {
      java.lang.Object ref = orderRejectedReson_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderRejectedReson_ = s;
        return s;
      }
    }
    /**
     * <code>string orderRejectedReson = 11;</code>
     * @return The bytes for orderRejectedReson.
     */
    public com.google.protobuf.ByteString
        getOrderRejectedResonBytes() {
      java.lang.Object ref = orderRejectedReson_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderRejectedReson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERTYPE_FIELD_NUMBER = 12;
    private volatile java.lang.Object orderType_;
    /**
     * <code>string orderType = 12;</code>
     * @return The orderType.
     */
    public java.lang.String getOrderType() {
      java.lang.Object ref = orderType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderType_ = s;
        return s;
      }
    }
    /**
     * <code>string orderType = 12;</code>
     * @return The bytes for orderType.
     */
    public com.google.protobuf.ByteString
        getOrderTypeBytes() {
      java.lang.Object ref = orderType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERPRICE_FIELD_NUMBER = 13;
    private double orderPrice_;
    /**
     * <code>double orderPrice = 13;</code>
     * @return The orderPrice.
     */
    public double getOrderPrice() {
      return orderPrice_;
    }

    public static final int ORDERVOLUME_FIELD_NUMBER = 14;
    private long orderVolume_;
    /**
     * <code>sint64 orderVolume = 14;</code>
     * @return The orderVolume.
     */
    public long getOrderVolume() {
      return orderVolume_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 15;
    private volatile java.lang.Object direction_;
    /**
     * <code>string direction = 15;</code>
     * @return The direction.
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      }
    }
    /**
     * <code>string direction = 15;</code>
     * @return The bytes for direction.
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXECSTATUS_FIELD_NUMBER = 16;
    private volatile java.lang.Object execStatus_;
    /**
     * <code>string execStatus = 16;</code>
     * @return The execStatus.
     */
    public java.lang.String getExecStatus() {
      java.lang.Object ref = execStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        execStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string execStatus = 16;</code>
     * @return The bytes for execStatus.
     */
    public com.google.protobuf.ByteString
        getExecStatusBytes() {
      java.lang.Object ref = execStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        execStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WITHDRAWFLAG_FIELD_NUMBER = 17;
    private boolean withdrawFlag_;
    /**
     * <code>bool withdrawFlag = 17;</code>
     * @return The withdrawFlag.
     */
    public boolean getWithdrawFlag() {
      return withdrawFlag_;
    }

    public static final int WITHDRAWVOLUME_FIELD_NUMBER = 18;
    private long withdrawVolume_;
    /**
     * <code>sint64 withdrawVolume = 18;</code>
     * @return The withdrawVolume.
     */
    public long getWithdrawVolume() {
      return withdrawVolume_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (boid_ != 0L) {
        output.writeSInt64(2, boid_);
      }
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, account_);
      }
      if (!getSecurityCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, securityCode_);
      }
      if (!getExchBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, exch_);
      }
      if (!getSecurityTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, securityType_);
      }
      if (!getTradeDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tradeDate_);
      }
      if (!getOrderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, orderId_);
      }
      if (!getOrderStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, orderStatus_);
      }
      if (!getOrderRejectedResonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, orderRejectedReson_);
      }
      if (!getOrderTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, orderType_);
      }
      if (orderPrice_ != 0D) {
        output.writeDouble(13, orderPrice_);
      }
      if (orderVolume_ != 0L) {
        output.writeSInt64(14, orderVolume_);
      }
      if (!getDirectionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, direction_);
      }
      if (!getExecStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, execStatus_);
      }
      if (withdrawFlag_ != false) {
        output.writeBool(17, withdrawFlag_);
      }
      if (withdrawVolume_ != 0L) {
        output.writeSInt64(18, withdrawVolume_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (boid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, boid_);
      }
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, account_);
      }
      if (!getSecurityCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, securityCode_);
      }
      if (!getExchBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, exch_);
      }
      if (!getSecurityTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, securityType_);
      }
      if (!getTradeDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tradeDate_);
      }
      if (!getOrderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, orderId_);
      }
      if (!getOrderStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, orderStatus_);
      }
      if (!getOrderRejectedResonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, orderRejectedReson_);
      }
      if (!getOrderTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, orderType_);
      }
      if (orderPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, orderPrice_);
      }
      if (orderVolume_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(14, orderVolume_);
      }
      if (!getDirectionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, direction_);
      }
      if (!getExecStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, execStatus_);
      }
      if (withdrawFlag_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(17, withdrawFlag_);
      }
      if (withdrawVolume_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(18, withdrawVolume_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO)) {
        return super.equals(obj);
      }
      com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO other = (com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO) obj;

      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (getBoid()
          != other.getBoid()) return false;
      if (!getAccount()
          .equals(other.getAccount())) return false;
      if (!getSecurityCode()
          .equals(other.getSecurityCode())) return false;
      if (!getExch()
          .equals(other.getExch())) return false;
      if (!getSecurityType()
          .equals(other.getSecurityType())) return false;
      if (!getTradeDate()
          .equals(other.getTradeDate())) return false;
      if (!getOrderId()
          .equals(other.getOrderId())) return false;
      if (!getOrderStatus()
          .equals(other.getOrderStatus())) return false;
      if (!getOrderRejectedReson()
          .equals(other.getOrderRejectedReson())) return false;
      if (!getOrderType()
          .equals(other.getOrderType())) return false;
      if (java.lang.Double.doubleToLongBits(getOrderPrice())
          != java.lang.Double.doubleToLongBits(
              other.getOrderPrice())) return false;
      if (getOrderVolume()
          != other.getOrderVolume()) return false;
      if (!getDirection()
          .equals(other.getDirection())) return false;
      if (!getExecStatus()
          .equals(other.getExecStatus())) return false;
      if (getWithdrawFlag()
          != other.getWithdrawFlag()) return false;
      if (getWithdrawVolume()
          != other.getWithdrawVolume()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + BOID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBoid());
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + SECURITY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityCode().hashCode();
      hash = (37 * hash) + EXCH_FIELD_NUMBER;
      hash = (53 * hash) + getExch().hashCode();
      hash = (37 * hash) + SECURITY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityType().hashCode();
      hash = (37 * hash) + TRADEDATE_FIELD_NUMBER;
      hash = (53 * hash) + getTradeDate().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId().hashCode();
      hash = (37 * hash) + ORDERSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getOrderStatus().hashCode();
      hash = (37 * hash) + ORDERREJECTEDRESON_FIELD_NUMBER;
      hash = (53 * hash) + getOrderRejectedReson().hashCode();
      hash = (37 * hash) + ORDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOrderType().hashCode();
      hash = (37 * hash) + ORDERPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOrderPrice()));
      hash = (37 * hash) + ORDERVOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderVolume());
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
      hash = (37 * hash) + EXECSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getExecStatus().hashCode();
      hash = (37 * hash) + WITHDRAWFLAG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getWithdrawFlag());
      hash = (37 * hash) + WITHDRAWVOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWithdrawVolume());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderBO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderBO)
        com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.purefun.fams.trade.order.pro.OrderBO_PRO.internal_static_OrderBO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.purefun.fams.trade.order.pro.OrderBO_PRO.internal_static_OrderBO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO.class, com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO.Builder.class);
      }

      // Construct using com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uuid_ = "";

        boid_ = 0L;

        account_ = "";

        securityCode_ = "";

        exch_ = "";

        securityType_ = "";

        tradeDate_ = "";

        orderId_ = "";

        orderStatus_ = "";

        orderRejectedReson_ = "";

        orderType_ = "";

        orderPrice_ = 0D;

        orderVolume_ = 0L;

        direction_ = "";

        execStatus_ = "";

        withdrawFlag_ = false;

        withdrawVolume_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.purefun.fams.trade.order.pro.OrderBO_PRO.internal_static_OrderBO_descriptor;
      }

      @java.lang.Override
      public com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO getDefaultInstanceForType() {
        return com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO.getDefaultInstance();
      }

      @java.lang.Override
      public com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO build() {
        com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO buildPartial() {
        com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO result = new com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO(this);
        result.uuid_ = uuid_;
        result.boid_ = boid_;
        result.account_ = account_;
        result.securityCode_ = securityCode_;
        result.exch_ = exch_;
        result.securityType_ = securityType_;
        result.tradeDate_ = tradeDate_;
        result.orderId_ = orderId_;
        result.orderStatus_ = orderStatus_;
        result.orderRejectedReson_ = orderRejectedReson_;
        result.orderType_ = orderType_;
        result.orderPrice_ = orderPrice_;
        result.orderVolume_ = orderVolume_;
        result.direction_ = direction_;
        result.execStatus_ = execStatus_;
        result.withdrawFlag_ = withdrawFlag_;
        result.withdrawVolume_ = withdrawVolume_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO) {
          return mergeFrom((com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO other) {
        if (other == com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.getBoid() != 0L) {
          setBoid(other.getBoid());
        }
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (!other.getSecurityCode().isEmpty()) {
          securityCode_ = other.securityCode_;
          onChanged();
        }
        if (!other.getExch().isEmpty()) {
          exch_ = other.exch_;
          onChanged();
        }
        if (!other.getSecurityType().isEmpty()) {
          securityType_ = other.securityType_;
          onChanged();
        }
        if (!other.getTradeDate().isEmpty()) {
          tradeDate_ = other.tradeDate_;
          onChanged();
        }
        if (!other.getOrderId().isEmpty()) {
          orderId_ = other.orderId_;
          onChanged();
        }
        if (!other.getOrderStatus().isEmpty()) {
          orderStatus_ = other.orderStatus_;
          onChanged();
        }
        if (!other.getOrderRejectedReson().isEmpty()) {
          orderRejectedReson_ = other.orderRejectedReson_;
          onChanged();
        }
        if (!other.getOrderType().isEmpty()) {
          orderType_ = other.orderType_;
          onChanged();
        }
        if (other.getOrderPrice() != 0D) {
          setOrderPrice(other.getOrderPrice());
        }
        if (other.getOrderVolume() != 0L) {
          setOrderVolume(other.getOrderVolume());
        }
        if (!other.getDirection().isEmpty()) {
          direction_ = other.direction_;
          onChanged();
        }
        if (!other.getExecStatus().isEmpty()) {
          execStatus_ = other.execStatus_;
          onChanged();
        }
        if (other.getWithdrawFlag() != false) {
          setWithdrawFlag(other.getWithdrawFlag());
        }
        if (other.getWithdrawVolume() != 0L) {
          setWithdrawVolume(other.getWithdrawVolume());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private long boid_ ;
      /**
       * <code>sint64 boid = 2;</code>
       * @return The boid.
       */
      public long getBoid() {
        return boid_;
      }
      /**
       * <code>sint64 boid = 2;</code>
       * @param value The boid to set.
       * @return This builder for chaining.
       */
      public Builder setBoid(long value) {
        
        boid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 boid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoid() {
        
        boid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>string account = 4;</code>
       * @return The account.
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account = 4;</code>
       * @return The bytes for account.
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account = 4;</code>
       * @param value The account to set.
       * @return This builder for chaining.
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>string account = 4;</code>
       * @param value The bytes for account to set.
       * @return This builder for chaining.
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object securityCode_ = "";
      /**
       * <code>string security_code = 5;</code>
       * @return The securityCode.
       */
      public java.lang.String getSecurityCode() {
        java.lang.Object ref = securityCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          securityCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string security_code = 5;</code>
       * @return The bytes for securityCode.
       */
      public com.google.protobuf.ByteString
          getSecurityCodeBytes() {
        java.lang.Object ref = securityCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string security_code = 5;</code>
       * @param value The securityCode to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        securityCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string security_code = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityCode() {
        
        securityCode_ = getDefaultInstance().getSecurityCode();
        onChanged();
        return this;
      }
      /**
       * <code>string security_code = 5;</code>
       * @param value The bytes for securityCode to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        securityCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exch_ = "";
      /**
       * <code>string exch = 6;</code>
       * @return The exch.
       */
      public java.lang.String getExch() {
        java.lang.Object ref = exch_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exch_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exch = 6;</code>
       * @return The bytes for exch.
       */
      public com.google.protobuf.ByteString
          getExchBytes() {
        java.lang.Object ref = exch_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exch_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exch = 6;</code>
       * @param value The exch to set.
       * @return This builder for chaining.
       */
      public Builder setExch(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exch = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearExch() {
        
        exch_ = getDefaultInstance().getExch();
        onChanged();
        return this;
      }
      /**
       * <code>string exch = 6;</code>
       * @param value The bytes for exch to set.
       * @return This builder for chaining.
       */
      public Builder setExchBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exch_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object securityType_ = "";
      /**
       * <code>string security_type = 7;</code>
       * @return The securityType.
       */
      public java.lang.String getSecurityType() {
        java.lang.Object ref = securityType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          securityType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string security_type = 7;</code>
       * @return The bytes for securityType.
       */
      public com.google.protobuf.ByteString
          getSecurityTypeBytes() {
        java.lang.Object ref = securityType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string security_type = 7;</code>
       * @param value The securityType to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        securityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string security_type = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityType() {
        
        securityType_ = getDefaultInstance().getSecurityType();
        onChanged();
        return this;
      }
      /**
       * <code>string security_type = 7;</code>
       * @param value The bytes for securityType to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        securityType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tradeDate_ = "";
      /**
       * <code>string tradeDate = 8;</code>
       * @return The tradeDate.
       */
      public java.lang.String getTradeDate() {
        java.lang.Object ref = tradeDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tradeDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tradeDate = 8;</code>
       * @return The bytes for tradeDate.
       */
      public com.google.protobuf.ByteString
          getTradeDateBytes() {
        java.lang.Object ref = tradeDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tradeDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tradeDate = 8;</code>
       * @param value The tradeDate to set.
       * @return This builder for chaining.
       */
      public Builder setTradeDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tradeDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tradeDate = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTradeDate() {
        
        tradeDate_ = getDefaultInstance().getTradeDate();
        onChanged();
        return this;
      }
      /**
       * <code>string tradeDate = 8;</code>
       * @param value The bytes for tradeDate to set.
       * @return This builder for chaining.
       */
      public Builder setTradeDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tradeDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>string orderId = 9;</code>
       * @return The orderId.
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderId = 9;</code>
       * @return The bytes for orderId.
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderId = 9;</code>
       * @param value The orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderId() {
        
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 9;</code>
       * @param value The bytes for orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object orderStatus_ = "";
      /**
       * <code>string orderStatus = 10;</code>
       * @return The orderStatus.
       */
      public java.lang.String getOrderStatus() {
        java.lang.Object ref = orderStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderStatus = 10;</code>
       * @return The bytes for orderStatus.
       */
      public com.google.protobuf.ByteString
          getOrderStatusBytes() {
        java.lang.Object ref = orderStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderStatus = 10;</code>
       * @param value The orderStatus to set.
       * @return This builder for chaining.
       */
      public Builder setOrderStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderStatus = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderStatus() {
        
        orderStatus_ = getDefaultInstance().getOrderStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string orderStatus = 10;</code>
       * @param value The bytes for orderStatus to set.
       * @return This builder for chaining.
       */
      public Builder setOrderStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderStatus_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object orderRejectedReson_ = "";
      /**
       * <code>string orderRejectedReson = 11;</code>
       * @return The orderRejectedReson.
       */
      public java.lang.String getOrderRejectedReson() {
        java.lang.Object ref = orderRejectedReson_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderRejectedReson_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderRejectedReson = 11;</code>
       * @return The bytes for orderRejectedReson.
       */
      public com.google.protobuf.ByteString
          getOrderRejectedResonBytes() {
        java.lang.Object ref = orderRejectedReson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderRejectedReson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderRejectedReson = 11;</code>
       * @param value The orderRejectedReson to set.
       * @return This builder for chaining.
       */
      public Builder setOrderRejectedReson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderRejectedReson_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderRejectedReson = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderRejectedReson() {
        
        orderRejectedReson_ = getDefaultInstance().getOrderRejectedReson();
        onChanged();
        return this;
      }
      /**
       * <code>string orderRejectedReson = 11;</code>
       * @param value The bytes for orderRejectedReson to set.
       * @return This builder for chaining.
       */
      public Builder setOrderRejectedResonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderRejectedReson_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object orderType_ = "";
      /**
       * <code>string orderType = 12;</code>
       * @return The orderType.
       */
      public java.lang.String getOrderType() {
        java.lang.Object ref = orderType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderType = 12;</code>
       * @return The bytes for orderType.
       */
      public com.google.protobuf.ByteString
          getOrderTypeBytes() {
        java.lang.Object ref = orderType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderType = 12;</code>
       * @param value The orderType to set.
       * @return This builder for chaining.
       */
      public Builder setOrderType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderType = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderType() {
        
        orderType_ = getDefaultInstance().getOrderType();
        onChanged();
        return this;
      }
      /**
       * <code>string orderType = 12;</code>
       * @param value The bytes for orderType to set.
       * @return This builder for chaining.
       */
      public Builder setOrderTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderType_ = value;
        onChanged();
        return this;
      }

      private double orderPrice_ ;
      /**
       * <code>double orderPrice = 13;</code>
       * @return The orderPrice.
       */
      public double getOrderPrice() {
        return orderPrice_;
      }
      /**
       * <code>double orderPrice = 13;</code>
       * @param value The orderPrice to set.
       * @return This builder for chaining.
       */
      public Builder setOrderPrice(double value) {
        
        orderPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double orderPrice = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderPrice() {
        
        orderPrice_ = 0D;
        onChanged();
        return this;
      }

      private long orderVolume_ ;
      /**
       * <code>sint64 orderVolume = 14;</code>
       * @return The orderVolume.
       */
      public long getOrderVolume() {
        return orderVolume_;
      }
      /**
       * <code>sint64 orderVolume = 14;</code>
       * @param value The orderVolume to set.
       * @return This builder for chaining.
       */
      public Builder setOrderVolume(long value) {
        
        orderVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 orderVolume = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderVolume() {
        
        orderVolume_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object direction_ = "";
      /**
       * <code>string direction = 15;</code>
       * @return The direction.
       */
      public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string direction = 15;</code>
       * @return The bytes for direction.
       */
      public com.google.protobuf.ByteString
          getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string direction = 15;</code>
       * @param value The direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirection() {
        
        direction_ = getDefaultInstance().getDirection();
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 15;</code>
       * @param value The bytes for direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        direction_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object execStatus_ = "";
      /**
       * <code>string execStatus = 16;</code>
       * @return The execStatus.
       */
      public java.lang.String getExecStatus() {
        java.lang.Object ref = execStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          execStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string execStatus = 16;</code>
       * @return The bytes for execStatus.
       */
      public com.google.protobuf.ByteString
          getExecStatusBytes() {
        java.lang.Object ref = execStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          execStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string execStatus = 16;</code>
       * @param value The execStatus to set.
       * @return This builder for chaining.
       */
      public Builder setExecStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        execStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string execStatus = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecStatus() {
        
        execStatus_ = getDefaultInstance().getExecStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string execStatus = 16;</code>
       * @param value The bytes for execStatus to set.
       * @return This builder for chaining.
       */
      public Builder setExecStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        execStatus_ = value;
        onChanged();
        return this;
      }

      private boolean withdrawFlag_ ;
      /**
       * <code>bool withdrawFlag = 17;</code>
       * @return The withdrawFlag.
       */
      public boolean getWithdrawFlag() {
        return withdrawFlag_;
      }
      /**
       * <code>bool withdrawFlag = 17;</code>
       * @param value The withdrawFlag to set.
       * @return This builder for chaining.
       */
      public Builder setWithdrawFlag(boolean value) {
        
        withdrawFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool withdrawFlag = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearWithdrawFlag() {
        
        withdrawFlag_ = false;
        onChanged();
        return this;
      }

      private long withdrawVolume_ ;
      /**
       * <code>sint64 withdrawVolume = 18;</code>
       * @return The withdrawVolume.
       */
      public long getWithdrawVolume() {
        return withdrawVolume_;
      }
      /**
       * <code>sint64 withdrawVolume = 18;</code>
       * @param value The withdrawVolume to set.
       * @return This builder for chaining.
       */
      public Builder setWithdrawVolume(long value) {
        
        withdrawVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 withdrawVolume = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearWithdrawVolume() {
        
        withdrawVolume_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OrderBO)
    }

    // @@protoc_insertion_point(class_scope:OrderBO)
    private static final com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO();
    }

    public static com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderBO>
        PARSER = new com.google.protobuf.AbstractParser<OrderBO>() {
      @java.lang.Override
      public OrderBO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderBO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderBO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderBO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.purefun.fams.trade.order.pro.OrderBO_PRO.OrderBO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderBO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderBO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rOrderBO.proto\"\330\002\n\007OrderBO\022\014\n\004uuid\030\001 \001(" +
      "\t\022\014\n\004boid\030\002 \001(\022\022\017\n\007account\030\004 \001(\t\022\025\n\rsecu" +
      "rity_code\030\005 \001(\t\022\014\n\004exch\030\006 \001(\t\022\025\n\rsecurit" +
      "y_type\030\007 \001(\t\022\021\n\ttradeDate\030\010 \001(\t\022\017\n\007order" +
      "Id\030\t \001(\t\022\023\n\013orderStatus\030\n \001(\t\022\032\n\022orderRe" +
      "jectedReson\030\013 \001(\t\022\021\n\torderType\030\014 \001(\t\022\022\n\n" +
      "orderPrice\030\r \001(\001\022\023\n\013orderVolume\030\016 \001(\022\022\021\n" +
      "\tdirection\030\017 \001(\t\022\022\n\nexecStatus\030\020 \001(\t\022\024\n\014" +
      "withdrawFlag\030\021 \001(\010\022\026\n\016withdrawVolume\030\022 \001" +
      "(\022B/\n com.purefun.fams.trade.order.proB\013" +
      "OrderBO_PROb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OrderBO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderBO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderBO_descriptor,
        new java.lang.String[] { "Uuid", "Boid", "Account", "SecurityCode", "Exch", "SecurityType", "TradeDate", "OrderId", "OrderStatus", "OrderRejectedReson", "OrderType", "OrderPrice", "OrderVolume", "Direction", "ExecStatus", "WithdrawFlag", "WithdrawVolume", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
