
server:
    port: 8901
    #port: ${random.int[10000,19999]}
    max-http-header-size: 8MB

eureka:
    instance:
        hostname: localhost
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 20
        instance-id: ${spring.application.name}-${Instance}:${server.port}
    client:
        registerWithEureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://${eureka.instance.hostname}:8888/eureka/

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/upstream?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        username: root
        password: jianghan0712
        driver-class-name: com.mysql.jdbc.Driver
        max-idle: 10
        max-wait: 10000
        initial-size: 5

mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.purefun.fams.domain
    global-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 0
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        field-strategy: 2
        #驼峰下划线转换
        db-column-underline: true
        #刷新mapper 调试神器
        refresh-mapper: true
        #逻辑删除配置（下面3个配置）
        logic-delete-value: 0
        logic-not-delete-value: 1
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: true

           